from contextlib import asynccontextmanager
import hmac
import json
import logging
from pathlib import Path

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

from backend.db import get_connection, get_metadata, initialize_database, next_data_version, set_metadata
from backend.models import (
    AuthResponse,
    DeltaResponse,
    ImportBatchRequest,
    ImportBatchResponse,
    LoginRequest,
    MockAnswerRequest,
    MockAttemptOut,
    MockSubmitResponse,
    MockTestIn,
    MockTestOut,
    QuestionIn,
    QuestionOut,
    RegisterRequest,
    ReportRequest,
    ReportOut,
    ReportResponse,
    ReportUpdateRequest,
    ReviewUpdateRequest,
    SearchMatch,
    SearchRequest,
    SearchResponse,
    SyllabusIn,
    SyllabusOut,
    UserCreate,
    UserOut,
    UserStats,
    UserUpdate,
    TopicNotesOut,
    FlashcardOut,
    TopicDetailResponse,
    TopicProgressIn,
    TopicOut,
    AiLessonOut,
    AiTutorAskIn,
    AiTutorAskOut,
)
from backend.repository import (
    answer_mock_question,
    create_mock_attempt,
    create_mock_test,
    create_user,
    delete_mock_test,
    delete_report,
    delete_syllabus,
    delete_user,
    get_mock_attempt,
    get_mock_test,
    get_question,
    get_syllabus,
    get_user,
    get_user_by_email,
    get_user_stats,
    insert_question,
    insert_syllabus,
    list_mock_tests,
    list_questions,
    list_questions_admin,
    list_reports,
    list_syllabus,
    list_users,
    search_questions,
    submit_mock_attempt,
    list_preparation_subjects,
    list_preparation_topics,
    get_preparation_topic,
    save_topic_progress,
    get_ai_lesson,
    ai_tutor_ask,
    update_mock_test,
    update_question,
    update_report_status,
    update_syllabus,
    update_user,
    utc_iso_now,
)
from backend.security import (
    create_session,
    device_hash,
    get_bearer_or_cookie_token,
    get_current_user,
    hash_password,
    normalize_email,
    rate_limit,
    require_admin_user,
    sign_payload,
    token_hash,
    validate_csrf_token,
    verify_password,
)
from backend.settings import settings
from backend.text import normalize_text


logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ADMIN_ASSETS = Path(__file__).resolve().parent / "admin_assets"
DASHBOARD_DIST = Path(__file__).resolve().parents[1] / "admin-dashboard" / "dist"
ARCHITECTURE_PAGE = PROJECT_ROOT / "index.html"
ARCHITECTURE_SPEC = PROJECT_ROOT / "ARCHITECTURE.md"

AI_DISCLAIMER = (
    "This answer was generated by an on-device AI model and may be incomplete "
    "or inaccurate. Please verify important facts with official sources such "
    "as Rajpatra or authoritative textbooks."
)


def startup() -> None:
    initialize_database()
    with get_connection() as connection:
        if not get_metadata(connection, "data_version", ""):
            set_metadata(connection, "data_version", "1")
        ensure_bootstrap_admin(connection)
        seed_sample_questions(connection)
        ensure_sample_mock_test(connection)
        seed_preparation_materials(connection)


def seed_preparation_materials(connection) -> None:
    """Pre-populate dynamic subject topics and flashcards for study preparation module."""
    cnt = connection.execute("SELECT COUNT(*) AS count FROM topic_notes").fetchone()["count"]
    if cnt > 0:
        return

    topics = [
        {
            "subject_id": "Constitution",
            "title": "Introduction to the Constitution of Nepal",
            "content_beginner": "The Constitution of Nepal is the supreme law of the land. It was promulgated on 20 September 2015 (3 Ashoj 2072 BS) by the Constituent Assembly.",
            "content_intermediate": "The current Constitution of Nepal consists of 35 Parts, 308 Articles, and 9 Schedules. It replaced the Interim Constitution of 2063 BS. It defines Nepal as a federal democratic republic with three levels of governance: Federal, Provincial, and Local.",
            "content_advanced": "The constitution was promulgated by the second Constituent Assembly under the presidency of Ram Baran Yadav and Prime Minister Sushil Koirala. It represents a historic transition to federalism, with key characteristics such as cooperative federalism, secularism, and constitutional guarantees for inclusion.",
            "revision_notes": "- Promulgation date: 2072 Ashoj 3 (20 Sept 2015)\n- Structure: 35 Parts, 308 Articles, 9 Schedules\n- Concept: Federal Democratic Republic, Secular state, 3 tiers of government",
            "flashcards": [
                {"front": "When was the current Constitution of Nepal promulgated?", "back": "2072 Ashoj 3 (September 20, 2015)"},
                {"front": "How many Articles are there in the Constitution of Nepal?", "back": "308 Articles (under 35 Parts and 9 Schedules)"}
            ]
        },
        {
            "subject_id": "Constitution",
            "title": "Fundamental Rights of Citizens",
            "content_beginner": "Fundamental Rights are basic human rights guaranteed by the constitution to every citizen. Part 3 of the Constitution of Nepal lists these rights.",
            "content_intermediate": "There are 31 Fundamental Rights guaranteed under Articles 16 to 46 in Part 3 of the Constitution of Nepal. These range from the Right to live with dignity (Art 16) to the Right to constitutional remedies (Art 46).",
            "content_advanced": "Unlike ordinary legal rights, fundamental rights are constitutional guarantees enforceable directly through the Supreme Court under Article 46. Key rights include the Right of victim of crime (Art 21), Right against torture (Art 22), and Right to free secondary education (Art 31).",
            "revision_notes": "- Rights: 31 fundamental rights\n- Location: Part 3, Articles 16-46\n- Key Article: Article 46 (Right to constitutional remedies via Supreme Court)",
            "flashcards": [
                {"front": "How many Fundamental Rights are guaranteed by the Constitution of Nepal?", "back": "31 rights (from Article 16 to 46)"},
                {"front": "Which article guarantees the Right to live with dignity?", "back": "Article 16 (no law shall make provision for capital punishment)"}
            ]
        },
        {
            "subject_id": "Geography",
            "title": "Mountains and Peaks of Nepal",
            "content_beginner": "Nepal is home to the highest mountains in the world. The northern border is dominated by the Himalayan range, including Mount Everest.",
            "content_intermediate": "Nepal contains 8 of the 14 highest peaks in the world (above 8,000 meters). This includes Mount Everest (8848.86m), Kangchenjunga (8586m), Lhotse (8516m), Makalu (8485m), Cho Oyu (8188m), Dhaulagiri (8167m), Manaslu (8163m), and Annapurna (8091m).",
            "content_advanced": "Mountain ranges are geographically categorized into sections such as Mahalangur range (home to Everest, Lhotse, Cho Oyu) and Annapurna range. In 2020, Nepal and China jointly announced Everest's official height as 8848.86 meters.",
            "revision_notes": "- World's highest peaks in Nepal: 8 peaks above 8,000m\n- Mount Everest height: 8848.86 meters\n- Mahalangur range: Home of Everest",
            "flashcards": [
                {"front": "What is the official height of Mount Everest?", "back": "8,848.86 meters (jointly announced in 2020)"},
                {"front": "How many peaks above 8,000m are in Nepal?", "back": "8 peaks out of 14 in the world"}
            ]
        },
        {
            "subject_id": "History",
            "title": "Unification Campaign of Nepal",
            "content_beginner": "Nepal was unified by King Prithvi Narayan Shah of Gorkha. Before unification, Nepal was divided into many small principalities (Baise and Chaubise states).",
            "content_intermediate": "The unification campaign started in 1744 AD (1801 BS) with the conquest of Nuwakot. It succeeded in capturing Kathmandu in 1768 AD and Bhaktapur in 1769 AD, establishing Kathmandu as the capital of the unified Kingdom of Nepal.",
            "content_advanced": "Key military figures who shaped the campaign include Kaji Kalu Pande (who died in the first battle of Kirtipur), Bhakti Thapa, and Amar Singh Thapa (who led the westward expansion against British East India forces).",
            "revision_notes": "- Unification starter: King Prithvi Narayan Shah of Gorkha\n- Campaign start: 1744 AD (Nuwakot conquest)\n- Capture of Kathmandu: 1768 AD",
            "flashcards": [
                {"front": "Who is the Father of Unification of modern Nepal?", "back": "King Prithvi Narayan Shah of Gorkha"},
                {"front": "In which year was Kathmandu conquered by Gorkhali forces?", "back": "1768 AD (1825 BS)"}
            ]
        }
    ]

    for t in topics:
        cursor = connection.execute(
            """
            INSERT INTO topic_notes (subject_id, title, content_beginner, content_intermediate, content_advanced, revision_notes, verified)
            VALUES (?, ?, ?, ?, ?, ?, 1)
            """,
            (t["subject_id"], t["title"], t["content_beginner"], t["content_intermediate"], t["content_advanced"], t["revision_notes"])
        )
        topic_id = cursor.lastrowid
        for f in t["flashcards"]:
            connection.execute(
                """
                INSERT INTO flashcards (topic_id, front, back)
                VALUES (?, ?, ?)
                """,
                (topic_id, f["front"], f["back"])
            )



def ensure_bootstrap_admin(connection) -> None:
    existing_admin = connection.execute(
        "SELECT id FROM app_users WHERE role = 'admin' LIMIT 1"
    ).fetchone()
    if existing_admin is not None:
        return
    connection.execute(
        """
        INSERT INTO app_users (email, password_hash, full_name, role, status)
        VALUES (?, ?, ?, 'admin', 'active')
        """,
        (
            normalize_email(settings.bootstrap_admin_email),
            hash_password(settings.bootstrap_admin_password),
            settings.bootstrap_admin_name,
        ),
    )


def seed_sample_questions(connection) -> None:
    """Auto-seed questions from data/sample_questions.json if table is empty."""
    count_row = connection.execute(
        "SELECT COUNT(*) AS cnt FROM loksewa_questions"
    ).fetchone()
    if int(count_row["cnt"]) > 0:
        return

    sample_path = PROJECT_ROOT / "data" / "sample_questions.json"
    if not sample_path.exists():
        logger.warning("sample_questions.json not found at %s — skipping seed", sample_path)
        return

    with open(sample_path, "r", encoding="utf-8") as fh:
        questions_data = json.load(fh)

    version = int(get_metadata(connection, "data_version", "1"))
    seeded = 0
    for item in questions_data:
        q = QuestionIn(
            question_text=item["question_text"],
            option_a=item["option_a"],
            option_b=item["option_b"],
            option_c=item["option_c"],
            option_d=item["option_d"],
            correct_option=item["correct_option"],
            explanation=item.get("explanation", ""),
            syllabus_category=item.get("syllabus_category", ""),
            source_name=item.get("source_name", "Sample seed data"),
            source_license=item.get("source_license", "Internal sample data"),
            source_year=item.get("source_year"),
            source_page=item.get("source_page"),
            verifier=item.get("verifier", "development_seed"),
            verified_at=item.get("verified_at"),
            verification_status="verified",
        )
        try:
            insert_question(connection, q, data_version=version)
            seeded += 1
        except Exception as exc:
            logger.warning("Failed to seed question: %s", exc)

    logger.info("Seeded %d questions from sample_questions.json", seeded)


def ensure_sample_mock_test(connection) -> None:
    """Create 3 diverse mock tests if none exist yet."""
    existing = connection.execute("SELECT id FROM mock_tests LIMIT 1").fetchone()
    if existing is not None:
        return

    mock_definitions = [
        {
            "title": "Constitution & Governance Practice",
            "description": "Focused practice on Constitution and Governance topics.",
            "categories": ["Constitution", "Governance"],
            "question_count": 20,
            "duration_minutes": 30,
        },
        {
            "title": "General Knowledge Mixed Set",
            "description": "Mixed practice covering General Knowledge, Geography, and History.",
            "categories": ["General Knowledge", "Geography", "History"],
            "question_count": 25,
            "duration_minutes": 45,
        },
        {
            "title": "Full Loksewa Practice Exam",
            "description": "Comprehensive practice exam covering all categories.",
            "categories": [],  # all categories
            "question_count": 50,
            "duration_minutes": 60,
        },
    ]

    for defn in mock_definitions:
        if defn["categories"]:
            placeholders = ", ".join("?" for _ in defn["categories"])
            rows = connection.execute(
                f"""
                SELECT id
                FROM loksewa_questions
                WHERE verification_status = 'verified'
                  AND syllabus_category IN ({placeholders})
                ORDER BY id ASC
                LIMIT ?
                """,
                (*defn["categories"], defn["question_count"]),
            ).fetchall()
        else:
            rows = connection.execute(
                """
                SELECT id
                FROM loksewa_questions
                WHERE verification_status = 'verified'
                ORDER BY id ASC
                LIMIT ?
                """,
                (defn["question_count"],),
            ).fetchall()

        if not rows:
            logger.info(
                "Skipping mock test '%s': not enough verified questions",
                defn["title"],
            )
            continue

        mock = MockTestIn(
            title=defn["title"],
            description=defn["description"],
            exam_level="General",
            exam_type="MCQ",
            syllabus_category=", ".join(defn["categories"]) if defn["categories"] else "Mixed",
            duration_minutes=defn["duration_minutes"],
            marks_per_correct=1.0,
            negative_marking_enabled=True,
            negative_marks_per_wrong=0.2,
            status="published",
            question_ids=[int(row["id"]) for row in rows],
        )
        create_mock_test(connection, mock, created_by=None)
        logger.info(
            "Created mock test '%s' with %d questions",
            defn["title"],
            len(rows),
        )


@asynccontextmanager
async def lifespan(_: FastAPI):
    # Validate settings on startup (fail-fast for security issues)
    from backend.settings import validate_settings
    validate_settings()
    startup()
    yield


app = FastAPI(
    title=settings.app_name,
    version="0.1.0",
    docs_url="/docs" if settings.environment != "production" else None,
    redoc_url="/redoc" if settings.environment != "production" else None,
    dependencies=[Depends(rate_limit), Depends(validate_csrf_token)],
    lifespan=lifespan,
)

# HTTPS redirect only in production (trusted proxy sets X-Forwarded-Proto)
if settings.environment == "production":

    @app.middleware("http")
    async def https_redirect_middleware(request: Request, call_next):
        proto = request.headers.get("x-forwarded-proto", "http")
        if proto != "https":
            # Redirect all HTTP requests to HTTPS
            redirect_url = f"https://{request.url.hostname}{request.url.path}"
            if request.url.query:
                redirect_url += f"?{request.url.query}"
            from fastapi.responses import RedirectResponse

            return RedirectResponse(url=redirect_url, status_code=307)
        return await call_next(request)


# Request size limiting middleware (10MB for imports, 1MB for other requests)
@app.middleware("http")
async def limit_request_size(request: Request, call_next):
    if request.method in ("POST", "PUT", "PATCH", "DELETE"):
        path = request.url.path
        limit = 10 * 1024 * 1024 if "import" in path else 1 * 1024 * 1024

        content_length = request.headers.get("content-length")
        if content_length:
            try:
                if int(content_length) > limit:
                    from fastapi.responses import JSONResponse
                    return JSONResponse(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        content={"detail": "Request body too large"},
                    )
            except ValueError:
                from fastapi.responses import JSONResponse
                return JSONResponse(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    content={"detail": "Invalid Content-Length header"},
                )

        # To prevent chunked encoding/slowloris bypass, wrap request receive
        original_receive = request._receive
        body_size = 0

        async def receive():
            nonlocal body_size
            message = await original_receive()
            if message["type"] == "http.request":
                body_size += len(message.get("body", b""))
                if body_size > limit:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail="Request body too large",
                    )
            return message

        request._receive = receive

    try:
        response = await call_next(request)
    except HTTPException as exc:
        if exc.status_code == status.HTTP_413_REQUEST_ENTITY_TOO_LARGE:
            from fastapi.responses import JSONResponse
            return JSONResponse(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                content={"detail": exc.detail},
            )
        raise exc
    return response


app.add_middleware(
    CORSMiddleware,
    allow_origins=list(settings.cors_origins),
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allow_headers=["Content-Type", "X-Admin-Token", "Authorization", "X-CSRF-Token"],
)

if ADMIN_ASSETS.exists():
    app.mount("/admin-assets", StaticFiles(directory=ADMIN_ASSETS), name="admin-assets")
if DASHBOARD_DIST.exists():
    app.mount("/dashboard", StaticFiles(directory=DASHBOARD_DIST, html=True), name="dashboard")


def require_admin_access(
    request: Request,
    x_admin_token: str | None = Header(default=None),
) -> UserOut | None:
    if x_admin_token and hmac.compare_digest(x_admin_token, settings.admin_token):
        return None
    return require_admin_user(request)


def set_auth_cookie(response: Response, token: str, expires_at: str) -> None:
    response.set_cookie(
        key="loksewa_session",
        value=token,
        httponly=True,
        secure=settings.environment == "production",
        samesite="lax",
        expires=expires_at,
        path="/",
    )


@app.get("/admin")
def admin_panel() -> FileResponse:
    index = ADMIN_ASSETS / "index.html"
    if not index.exists():
        raise HTTPException(status_code=404, detail="Admin assets not found")
    return FileResponse(index)


@app.get("/")
@app.get("/architecture")
def architecture_page() -> FileResponse:
    if not ARCHITECTURE_PAGE.exists():
        raise HTTPException(status_code=404, detail="Architecture page not found")
    return FileResponse(ARCHITECTURE_PAGE)


@app.get("/architecture.md")
def architecture_markdown() -> PlainTextResponse:
    if not ARCHITECTURE_SPEC.exists():
        raise HTTPException(status_code=404, detail="Architecture spec not found")
    return PlainTextResponse(ARCHITECTURE_SPEC.read_text(encoding="utf-8"))


@app.get("/healthz")
def healthz() -> dict[str, str]:
    return {"status": "ok", "environment": settings.environment}


@app.post("/v1/auth/register", response_model=AuthResponse, status_code=status.HTTP_201_CREATED)
def register(payload: RegisterRequest, response: Response) -> AuthResponse:
    with get_connection() as connection:
        if get_user_by_email(connection, payload.email):
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Email already registered")
        user = create_user(
            connection,
            UserCreate(
                email=payload.email,
                password=payload.password,
                full_name=payload.full_name,
                role="student",
                status="active",
            ),
        )
        token, expires_at, csrf_token = create_session(connection, user.id, "mobile")
    set_auth_cookie(response, token, expires_at)
    # Return CSRF token to client for subsequent state-changing requests
    response.set_cookie(
        key="loksewa_csrf",
        value=csrf_token,
        httponly=False,  # Must be readable by JS for XHR double-submit
        secure=settings.environment == "production",
        samesite="strict",
        expires=expires_at,
        path="/",
    )
    return AuthResponse(token=token, user=user, expires_at=expires_at)


@app.post("/v1/auth/login", response_model=AuthResponse)
def login(payload: LoginRequest, response: Response) -> AuthResponse:
    with get_connection() as connection:
        row = get_user_by_email(connection, payload.email)
        if row is None or row["status"] != "active" or not verify_password(payload.password, row["password_hash"]):
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid email or password")
        user = UserOut(
            id=row["id"],
            email=row["email"],
            full_name=row["full_name"],
            role=row["role"],
            status=row["status"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            last_login_at=row["last_login_at"],
        )
        if payload.client_type == "admin" and user.role != "admin":
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Admin account required")
        token, expires_at, csrf_token = create_session(connection, user.id, payload.client_type)
    set_auth_cookie(response, token, expires_at)
    response.set_cookie(
        key="loksewa_csrf",
        value=csrf_token,
        httponly=False,
        secure=settings.environment == "production",
        samesite="strict",
        expires=expires_at,
        path="/",
    )
    return AuthResponse(token=token, user=user, expires_at=expires_at)


@app.get("/v1/auth/me", response_model=UserOut)
def me(user: UserOut = Depends(get_current_user)) -> UserOut:
    return user


@app.post("/v1/auth/logout", status_code=status.HTTP_204_NO_CONTENT)
def logout(request: Request, response: Response) -> Response:
    token = get_bearer_or_cookie_token(request)
    if token:
        with get_connection() as connection:
            connection.execute(
                "UPDATE auth_sessions SET revoked_at = CURRENT_TIMESTAMP WHERE token_hash = ?",
                (token_hash(token),),
            )
    response.delete_cookie("loksewa_session", path="/")
    response.status_code = status.HTTP_204_NO_CONTENT
    return response


@app.get("/v1/metadata")
def metadata() -> dict[str, str]:
    with get_connection() as connection:
        return {
            "schema_version": get_metadata(connection, "schema_version", "1"),
            "data_version": get_metadata(connection, "data_version", "1"),
            "database_kind": get_metadata(connection, "database_kind", "loksewa_backend"),
        }


@app.post("/v1/search", response_model=SearchResponse)
def search(payload: SearchRequest) -> SearchResponse:
    limit = min(payload.limit, settings.max_search_limit)
    with get_connection() as connection:
        raw_matches = search_questions(connection, payload.query, limit=limit)

    matches = [
        SearchMatch(question=question, bm25_score=bm25_score, similarity=similarity)
        for question, bm25_score, similarity in raw_matches
    ]

    best = matches[0].similarity if matches else 0.0
    if best >= settings.high_confidence_threshold:
        return SearchResponse(
            answer_source="verified_db",
            threshold_reason=f"Best trigram similarity {best:.2f} reached verified threshold.",
            query=payload.query,
            matches=matches,
        )

    if best >= settings.medium_confidence_threshold and payload.allow_ai_fallback:
        return SearchResponse(
            answer_source="ai_assisted",
            threshold_reason=f"Best trigram similarity {best:.2f} reached context threshold.",
            query=payload.query,
            matches=matches,
            disclaimer=AI_DISCLAIMER,
        )

    if payload.allow_ai_fallback:
        return SearchResponse(
            answer_source="ai_only",
            threshold_reason="No verified match passed the context threshold.",
            query=payload.query,
            matches=matches,
            disclaimer=AI_DISCLAIMER,
        )

    return SearchResponse(
        answer_source="uncertain",
        threshold_reason="No verified match and AI fallback is disabled.",
        query=payload.query,
        matches=matches,
    )


@app.get("/v1/questions", response_model=dict)
def questions(
    category: str | None = None,
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=20, ge=1, le=100),
) -> dict:
    with get_connection() as connection:
        all_items = list_questions(connection, category=category, limit=per_page * page)
        total = len(all_items)
        start = (page - 1) * per_page
        page_items = all_items[start:start + per_page]
        return {
            "page": page,
            "per_page": per_page,
            "total": total,
            "items": [item.model_dump(mode="json") for item in page_items],
        }


@app.get("/v1/questions/{question_id}", response_model=QuestionOut)
def question_detail(question_id: int) -> QuestionOut:
    with get_connection() as connection:
        question = get_question(connection, question_id)
    if question is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
    return question


@app.get("/v1/stats/me", response_model=UserStats)
def user_stats(user: UserOut = Depends(get_current_user)) -> UserStats:
    with get_connection() as connection:
        stats = get_user_stats(connection, user.id)
    return UserStats(**stats)


@app.get("/v1/mock-tests", response_model=list[MockTestOut])
def public_mock_tests(limit: int = Query(default=100, ge=1, le=500)) -> list[MockTestOut]:
    with get_connection() as connection:
        return list_mock_tests(connection, status="published", limit=limit)


@app.post("/v1/mock-tests/{mock_test_id}/start", response_model=MockAttemptOut, status_code=status.HTTP_201_CREATED)
def start_mock_test(mock_test_id: int, user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    with get_connection() as connection:
        attempt = create_mock_attempt(connection, mock_test_id, user.id)
    if attempt is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Published mock test not found")
    return attempt


@app.get("/v1/mock-attempts/{attempt_id}", response_model=MockAttemptOut)
def mock_attempt_detail(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    with get_connection() as connection:
        attempt = get_mock_attempt(connection, attempt_id, user_id=user.id, include_questions=True)
    if attempt is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attempt not found")
    return attempt


@app.post("/v1/mock-attempts/{attempt_id}/answers", response_model=MockAttemptOut)
def answer_mock(attempt_id: int, payload: MockAnswerRequest, user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    with get_connection() as connection:
        attempt = answer_mock_question(connection, attempt_id, user.id, payload)
    if attempt is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Cannot answer this question")
    return attempt


@app.post("/v1/mock-attempts/{attempt_id}/submit", response_model=MockSubmitResponse)
def submit_mock(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockSubmitResponse:
    with get_connection() as connection:
        result = submit_mock_attempt(connection, attempt_id, user.id)
    if result is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attempt not found")
    return result


@app.get("/v1/sync/delta", response_model=DeltaResponse)
def sync_delta(
    since_version: int = Query(default=0, ge=0),
    limit: int = Query(default=500, ge=1, le=5000),
) -> DeltaResponse:
    with get_connection() as connection:
        to_version = int(get_metadata(connection, "data_version", "1"))
        questions = list_questions(connection, since_version=since_version, limit=limit)

    payload = {
        "from_version": since_version,
        "to_version": to_version,
        "questions": [question.model_dump(mode="json") for question in questions],
    }
    return DeltaResponse(
        from_version=since_version,
        to_version=to_version,
        questions=questions,
        signature=sign_payload(payload),
    )


@app.post("/v1/reports", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
def create_report(payload: ReportRequest) -> ReportResponse:
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO user_reports (
                question_id,
                scanned_text,
                report_type,
                message,
                contact,
                device_hash
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                payload.question_id,
                payload.scanned_text,
                payload.report_type,
                payload.message,
                payload.contact,
                device_hash(payload.device_id),
            ),
        )
        report_id = int(cursor.lastrowid)
    return ReportResponse(report_id=report_id, status="open")


@app.get(
    "/v1/admin/questions",
    response_model=list[QuestionOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_questions(
    verification_status: str | None = None,
    category: str | None = None,
    query: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[QuestionOut]:
    with get_connection() as connection:
        return list_questions_admin(
            connection,
            status=verification_status,
            category=category,
            query=query,
            limit=limit,
        )


@app.post(
    "/v1/admin/questions",
    response_model=QuestionOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_question(payload: QuestionIn) -> QuestionOut:
    with get_connection() as connection:
        version = next_data_version(connection)
        question_id = insert_question(connection, payload, data_version=version)
        created = get_question(connection, question_id)
    if created is None:
        raise HTTPException(status_code=500, detail="Question insert failed")
    return created


@app.get(
    "/v1/admin/questions/{question_id}",
    response_model=QuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_get_question(question_id: int) -> QuestionOut:
    return question_detail(question_id)


@app.put(
    "/v1/admin/questions/{question_id}",
    response_model=QuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_question(question_id: int, payload: QuestionIn) -> QuestionOut:
    with get_connection() as connection:
        version = next_data_version(connection)
        updated = update_question(connection, question_id, payload, data_version=version)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
    return updated


@app.post(
    "/v1/admin/import-batch",
    response_model=ImportBatchResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_import_batch(payload: ImportBatchRequest) -> ImportBatchResponse:
    imported_count = 0
    rejected_count = 0

    with get_connection() as connection:
        version = next_data_version(connection)
        cursor = connection.execute(
            """
            INSERT INTO import_batches (
                batch_name,
                source_name,
                source_url,
                source_license,
                verifier
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                payload.batch_name,
                payload.source_name,
                payload.source_url,
                payload.source_license,
                payload.verifier,
            ),
        )
        batch_id = int(cursor.lastrowid)

        for question in payload.questions:
            if not question.source_name:
                question.source_name = payload.source_name
            if not question.source_url:
                question.source_url = payload.source_url
            if not question.source_license:
                question.source_license = payload.source_license
            if not question.verifier:
                question.verifier = payload.verifier
            try:
                insert_question(
                    connection,
                    question,
                    data_version=version,
                    import_batch_id=batch_id,
                )
                imported_count += 1
            except Exception:
                rejected_count += 1

        connection.execute(
            """
            UPDATE import_batches
            SET imported_count = ?, rejected_count = ?
            WHERE id = ?
            """,
            (imported_count, rejected_count, batch_id),
        )

    return ImportBatchResponse(
        batch_id=batch_id,
        imported_count=imported_count,
        rejected_count=rejected_count,
        data_version=version,
    )


@app.delete(
    "/v1/admin/questions/{question_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_question(question_id: int) -> Response:
    with get_connection() as connection:
        now = utc_iso_now()
        cursor = connection.execute(
            "UPDATE loksewa_questions SET verification_status = 'rejected', deleted_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
            (now, question_id),
        )
        if cursor.rowcount == 0:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
        next_data_version(connection)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.post(
    "/v1/admin/questions/{question_id}/review",
    response_model=QuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_review_question(question_id: int, payload: ReviewUpdateRequest) -> QuestionOut:
    with get_connection() as connection:
        version = next_data_version(connection)
        cursor = connection.execute(
            """
            UPDATE loksewa_questions
            SET
                verification_status = ?,
                source_name = CASE WHEN ? != '' THEN ? ELSE source_name END,
                source_url = CASE WHEN ? != '' THEN ? ELSE source_url END,
                source_license = CASE WHEN ? != '' THEN ? ELSE source_license END,
                verifier = CASE WHEN ? != '' THEN ? ELSE verifier END,
                verified_at = COALESCE(?, verified_at),
                data_version = ?,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (
                payload.verification_status,
                payload.source_name,
                payload.source_name,
                payload.source_url,
                payload.source_url,
                payload.source_license,
                payload.source_license,
                payload.verifier,
                payload.verifier,
                payload.verified_at,
                version,
                question_id,
            ),
        )
        if cursor.rowcount == 0:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
        reviewed = get_question(connection, question_id)
    if reviewed is None:
        raise HTTPException(status_code=500, detail="Review update failed")
    return reviewed


@app.get(
    "/v1/admin/syllabus",
    response_model=list[SyllabusOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_syllabus(category: str | None = None, limit: int = Query(default=200, ge=1, le=1000)) -> list[SyllabusOut]:
    with get_connection() as connection:
        return list_syllabus(connection, category=category, limit=limit)


@app.post(
    "/v1/admin/syllabus",
    response_model=SyllabusOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_syllabus(payload: SyllabusIn) -> SyllabusOut:
    with get_connection() as connection:
        syllabus_id = insert_syllabus(connection, payload)
        created = get_syllabus(connection, syllabus_id)
    if created is None:
        raise HTTPException(status_code=500, detail="Syllabus insert failed")
    return created


@app.put(
    "/v1/admin/syllabus/{syllabus_id}",
    response_model=SyllabusOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_syllabus(syllabus_id: int, payload: SyllabusIn) -> SyllabusOut:
    with get_connection() as connection:
        updated = update_syllabus(connection, syllabus_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Syllabus entry not found")
    return updated


@app.delete(
    "/v1/admin/syllabus/{syllabus_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_syllabus(syllabus_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_syllabus(connection, syllabus_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Syllabus entry not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/reports",
    response_model=list[ReportOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_reports(report_status: str | None = None, limit: int = Query(default=200, ge=1, le=1000)) -> list[ReportOut]:
    with get_connection() as connection:
        return list_reports(connection, status=report_status, limit=limit)


@app.put(
    "/v1/admin/reports/{report_id}",
    response_model=ReportOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_report(report_id: int, payload: ReportUpdateRequest) -> ReportOut:
    with get_connection() as connection:
        updated = update_report_status(connection, report_id, payload.status)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return updated


@app.delete(
    "/v1/admin/reports/{report_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_report(report_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_report(connection, report_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/users",
    response_model=list[UserOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_users(
    role: str | None = None,
    user_status: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[UserOut]:
    with get_connection() as connection:
        return list_users(connection, role=role, status=user_status, limit=limit)


@app.post(
    "/v1/admin/users",
    response_model=UserOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_user(payload: UserCreate) -> UserOut:
    with get_connection() as connection:
        if get_user_by_email(connection, payload.email):
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Email already exists")
        return create_user(connection, payload)


@app.put(
    "/v1/admin/users/{user_id}",
    response_model=UserOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_user(user_id: int, payload: UserUpdate) -> UserOut:
    with get_connection() as connection:
        updated = update_user(connection, user_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return updated


@app.delete(
    "/v1/admin/users/{user_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_user(user_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_user(connection, user_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/mock-tests",
    response_model=list[MockTestOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_mock_tests(mock_status: str | None = None, limit: int = Query(default=200, ge=1, le=1000)) -> list[MockTestOut]:
    with get_connection() as connection:
        return list_mock_tests(connection, status=mock_status, limit=limit)


@app.post(
    "/v1/admin/mock-tests",
    response_model=MockTestOut,
    status_code=status.HTTP_201_CREATED,
)
def admin_create_mock_test(payload: MockTestIn, admin: UserOut | None = Depends(require_admin_access)) -> MockTestOut:
    with get_connection() as connection:
        return create_mock_test(connection, payload, created_by=None if admin is None else admin.id)


@app.put(
    "/v1/admin/mock-tests/{mock_test_id}",
    response_model=MockTestOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_mock_test(mock_test_id: int, payload: MockTestIn) -> MockTestOut:
    with get_connection() as connection:
        updated = update_mock_test(connection, mock_test_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Mock test not found")
    return updated


@app.delete(
    "/v1/admin/mock-tests/{mock_test_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_mock_test(mock_test_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_mock_test(connection, mock_test_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Mock test not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get("/v1/categories")
def categories() -> list[dict[str, object]]:
    with get_connection() as connection:
        rows = connection.execute(
            """
            SELECT syllabus_category AS category, COUNT(*) AS total
            FROM loksewa_questions
            WHERE verification_status = 'verified'
            GROUP BY syllabus_category
            ORDER BY total DESC, category ASC
            """
        ).fetchall()
    return [{"category": row["category"], "total": row["total"]} for row in rows]


@app.get("/v1/preparation/subjects", response_model=list[str])
def preparation_subjects() -> list[str]:
    return list_preparation_subjects()


@app.get("/v1/preparation/subjects/{subject_id}/topics", response_model=list[TopicOut])
def preparation_topics(subject_id: str, user: UserOut = Depends(get_current_user)) -> list[TopicOut]:
    with get_connection() as connection:
        topics = list_preparation_topics(connection, subject_id, user.id)
    return [TopicOut(**t) for t in topics]


@app.get("/v1/preparation/topics/{topic_id}", response_model=TopicDetailResponse)
def preparation_topic_detail(topic_id: int, user: UserOut = Depends(get_current_user)) -> TopicDetailResponse:
    with get_connection() as connection:
        detail = get_preparation_topic(connection, topic_id, user.id)
    if detail is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Topic not found")
    return TopicDetailResponse(**detail)


@app.post("/v1/preparation/topics/{topic_id}/progress", status_code=status.HTTP_204_NO_CONTENT)
def update_topic_progress(topic_id: int, payload: TopicProgressIn, user: UserOut = Depends(get_current_user)) -> Response:
    with get_connection() as connection:
        save_topic_progress(connection, user.id, topic_id, payload.completion_percentage)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get("/v1/questions/{question_id}/ai-lesson", response_model=AiLessonOut)
def question_ai_lesson(question_id: int) -> AiLessonOut:
    with get_connection() as connection:
        lesson = get_ai_lesson(connection, question_id)
    if lesson is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
    return AiLessonOut(**lesson)


@app.post("/v1/ai-tutor/ask", response_model=AiTutorAskOut)
def ask_ai_tutor(payload: AiTutorAskIn) -> AiTutorAskOut:
    with get_connection() as connection:
        ans = ai_tutor_ask(connection, payload.query)
    return AiTutorAskOut(**ans)


# /api compatibility routes matching ARCHITECTURE.md exactly.


@app.post("/api/auth/register", response_model=AuthResponse, status_code=status.HTTP_201_CREATED)
def api_auth_register(payload: RegisterRequest, response: Response) -> AuthResponse:
    return register(payload, response)


@app.post("/api/auth/login", response_model=AuthResponse)
def api_auth_login(payload: LoginRequest, response: Response) -> AuthResponse:
    return login(payload, response)


@app.post("/api/auth/refresh", response_model=AuthResponse)
def api_auth_refresh(response: Response, user: UserOut = Depends(get_current_user)) -> AuthResponse:
    with get_connection() as connection:
        current = get_user(connection, user.id)
        if current is None:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")
        token, expires_at, csrf_token = create_session(connection, user.id, "mobile")
    set_auth_cookie(response, token, expires_at)
    response.set_cookie(
        key="loksewa_csrf",
        value=csrf_token,
        httponly=False,
        secure=settings.environment == "production",
        samesite="strict",
        expires=expires_at,
        path="/",
    )
    return AuthResponse(token=token, user=current, expires_at=expires_at)


@app.post("/api/auth/logout", status_code=status.HTTP_204_NO_CONTENT)
def api_auth_logout(request: Request, response: Response) -> Response:
    return logout(request, response)


@app.get("/api/users/me", response_model=UserOut)
def api_users_me(user: UserOut = Depends(get_current_user)) -> UserOut:
    return user


@app.put("/api/users/me", response_model=UserOut)
def api_users_me_update(payload: UserUpdate, user: UserOut = Depends(get_current_user)) -> UserOut:
    safe_payload = UserUpdate(
        email=payload.email,
        full_name=payload.full_name,
        password=payload.password,
        role=None,
        status=None,
    )
    with get_connection() as connection:
        updated = update_user(connection, user.id, safe_payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return updated


@app.get("/api/subjects")
def api_subjects() -> list[dict[str, str]]:
    return [{"id": subject, "name": subject} for subject in list_preparation_subjects()]


@app.get("/api/subjects/{subject_id}/topics", response_model=list[TopicOut])
def api_subject_topics(subject_id: str, user: UserOut = Depends(get_current_user)) -> list[TopicOut]:
    return preparation_topics(subject_id, user)


@app.get("/api/topics/{topic_id}/notes", response_model=TopicDetailResponse)
def api_topic_notes(topic_id: int, user: UserOut = Depends(get_current_user)) -> TopicDetailResponse:
    return preparation_topic_detail(topic_id, user)


@app.get("/api/topics/{topic_id}", response_model=TopicDetailResponse)
def api_topic_detail(topic_id: int, user: UserOut = Depends(get_current_user)) -> TopicDetailResponse:
    return preparation_topic_detail(topic_id, user)


@app.get("/api/questions/search", response_model=SearchResponse)
def api_questions_search(q: str = Query(min_length=3), limit: int = Query(default=3, ge=1, le=10)) -> SearchResponse:
    return search(SearchRequest(query=q, limit=limit, allow_ai_fallback=True))


@app.get("/api/questions", response_model=dict)
def api_questions(
    subject: str | None = None,
    topic: str | None = None,
    difficulty: str | None = None,
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=20, ge=1, le=100),
) -> dict:
    return questions(category=topic or subject, page=page, per_page=per_page)


@app.get("/api/questions/{question_id}", response_model=QuestionOut)
def api_question_detail(question_id: int) -> QuestionOut:
    return question_detail(question_id)


@app.get("/api/questions/{question_id}/answer")
def api_question_answer(question_id: int) -> dict[str, object]:
    question = question_detail(question_id)
    correct_text = getattr(question, f"option_{question.correct_option.lower()}")
    return {
        "question_id": question.id,
        "answer_source": "verified_db",
        "correct_option": question.correct_option,
        "correct_answer": correct_text,
        "explanation": question.explanation,
        "source_name": question.source_name,
        "source_year": question.source_year,
    }


@app.post("/api/scan")
def api_scan(payload: dict[str, object]) -> dict[str, object]:
    scanned_text = str(
        payload.get("scanned_text")
        or payload.get("text")
        or payload.get("query")
        or ""
    ).strip()
    if len(scanned_text) < 3:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="scanned_text is required")

    result = search(SearchRequest(query=scanned_text, limit=3, allow_ai_fallback=True))
    matched_question_id = result.matches[0].question.id if result.matches else None
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO scan_history (
                scanned_text,
                normalized_scanned_text,
                matched_question_id,
                answer_source
            )
            VALUES (?, ?, ?, ?)
            """,
            (scanned_text, normalize_text(scanned_text), matched_question_id, result.answer_source),
        )
        scan_id = int(cursor.lastrowid)
    return {
        "id": scan_id,
        "status": "completed",
        "result": result.model_dump(mode="json"),
    }


@app.get("/api/scan/{scan_id}")
def api_scan_detail(scan_id: int) -> dict[str, object]:
    with get_connection() as connection:
        row = connection.execute(
            """
            SELECT id, scanned_text, matched_question_id, answer_source, created_at
            FROM scan_history
            WHERE id = ?
            """,
            (scan_id,),
        ).fetchone()
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Scan not found")
    return dict(row)


@app.get("/api/scan/{scan_id}/result")
def api_scan_result(scan_id: int) -> dict[str, object]:
    detail = api_scan_detail(scan_id)
    question = None
    if detail.get("matched_question_id"):
        question = question_detail(int(detail["matched_question_id"])).model_dump(mode="json")
    return {
        "scan": detail,
        "question": question,
    }


@app.post("/api/lessons/generate", response_model=AiLessonOut)
def api_lesson_generate(payload: dict[str, object]) -> AiLessonOut:
    raw_id = payload.get("question_id") or payload.get("questionId")
    if raw_id is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="question_id is required")
    return question_ai_lesson(int(raw_id))


@app.get("/api/lessons/{question_id}", response_model=AiLessonOut)
def api_lesson_detail(question_id: int) -> AiLessonOut:
    return question_ai_lesson(question_id)


@app.get("/api/flashcards", response_model=list[FlashcardOut])
def api_flashcards(topic: str | None = None, limit: int = Query(default=50, ge=1, le=200)) -> list[FlashcardOut]:
    with get_connection() as connection:
        if topic and topic.isdigit():
            rows = connection.execute(
                "SELECT id, question_id, topic_id, front, back FROM flashcards WHERE topic_id = ? LIMIT ?",
                (int(topic), limit),
            ).fetchall()
        elif topic:
            rows = connection.execute(
                """
                SELECT f.id, f.question_id, f.topic_id, f.front, f.back
                FROM flashcards f
                JOIN topic_notes t ON t.id = f.topic_id
                WHERE t.subject_id = ? OR t.title LIKE ?
                LIMIT ?
                """,
                (topic, f"%{topic}%", limit),
            ).fetchall()
        else:
            rows = connection.execute(
                "SELECT id, question_id, topic_id, front, back FROM flashcards LIMIT ?",
                (limit,),
            ).fetchall()
    return [FlashcardOut(**dict(row)) for row in rows]


@app.post("/api/flashcards/{flashcard_id}/review")
def api_flashcard_review(flashcard_id: int, payload: dict[str, object], user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    return {
        "flashcard_id": flashcard_id,
        "user_id": user.id,
        "status": "recorded",
        "rating": payload.get("rating"),
    }


@app.get("/api/progress", response_model=UserStats)
def api_progress(user: UserOut = Depends(get_current_user)) -> UserStats:
    return user_stats(user)


@app.put("/api/progress/{topic_id}", status_code=status.HTTP_204_NO_CONTENT)
def api_progress_update(topic_id: int, payload: TopicProgressIn, user: UserOut = Depends(get_current_user)) -> Response:
    return update_topic_progress(topic_id, payload, user)


@app.post("/api/tutor/chat", response_model=AiTutorAskOut)
def api_tutor_chat(payload: dict[str, object]) -> AiTutorAskOut:
    query = str(payload.get("query") or payload.get("message") or "").strip()
    if len(query) < 2:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="query is required")
    return ask_ai_tutor(AiTutorAskIn(query=query))


@app.get("/api/tutor/conversations")
def api_tutor_conversations(user: UserOut = Depends(get_current_user)) -> list[dict[str, object]]:
    return []


@app.post("/api/tutor/conversations", status_code=status.HTTP_201_CREATED)
def api_tutor_create_conversation(user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    return {"id": "local-session", "user_id": user.id, "title": "Local tutor session", "messages": []}


@app.get("/api/tutor/conversations/{conversation_id}/messages")
def api_tutor_messages(conversation_id: str, user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    return {"id": conversation_id, "user_id": user.id, "messages": []}


@app.get("/api/tests", response_model=list[MockTestOut])
def api_tests(limit: int = Query(default=100, ge=1, le=500)) -> list[MockTestOut]:
    return public_mock_tests(limit)


@app.post("/api/tests/start", response_model=MockAttemptOut, status_code=status.HTTP_201_CREATED)
def api_tests_start(payload: dict[str, object], user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    raw_id = payload.get("mock_test_id") or payload.get("test_id") or payload.get("id")
    if raw_id is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="mock_test_id is required")
    return start_mock_test(int(raw_id), user)


@app.post("/api/tests/{attempt_id}/submit", response_model=MockSubmitResponse)
def api_tests_submit(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockSubmitResponse:
    return submit_mock(attempt_id, user)


@app.get("/api/tests/{attempt_id}/results", response_model=MockSubmitResponse)
def api_tests_results(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockSubmitResponse:
    with get_connection() as connection:
        result = submit_mock_attempt(connection, attempt_id, user.id)
    if result is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attempt not found")
    return result


@app.get("/api/analytics/stats", response_model=UserStats)
def api_analytics_stats(user: UserOut = Depends(get_current_user)) -> UserStats:
    return user_stats(user)


@app.get("/api/analytics/weaknesses")
def api_analytics_weaknesses(user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    stats = user_stats(user)
    return {
        "weaknesses": stats.categories_studied[:3],
        "message": "Review categories where recent mock answers were incorrect or unanswered.",
    }


@app.get("/api/analytics/recommendations")
def api_analytics_recommendations(user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    stats = user_stats(user)
    subjects = list_preparation_subjects()
    studied = set(stats.categories_studied)
    recommended = [subject for subject in subjects if subject not in studied][:3]
    return {
        "recommendations": recommended,
        "message": "Continue with verified topic notes, flashcards, and timed mock tests.",
    }
