from contextlib import asynccontextmanager
import asyncio
import hmac
import json
import logging
import sqlite3
from pathlib import Path
from urllib.parse import urlparse

from fastapi import Depends, FastAPI, Header, HTTPException, Query, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles

from backend.db import get_connection, get_metadata, initialize_database, next_data_version, set_metadata
from backend.models import (
    AuthResponse,
    DeltaResponse,
    ImportBatchRequest,
    ImportBatchResponse,
    LoginRequest,
    MockAnswerRequest,
    MockAttemptOut,
    MockSubmitResponse,
    MockTestIn,
    MockTestOut,
    QuestionIn,
    QuestionOut,
    RegisterRequest,
    ReportRequest,
    ReportOut,
    ReportResponse,
    ReportUpdateRequest,
    ReviewUpdateRequest,
    SearchMatch,
    SearchRequest,
    SearchResponse,
    ScrapedDocumentOut,
    ScraperRunOut,
    ScraperRunRequest,
    ScraperSourceIn,
    ScraperSourceOut,
    SyllabusIn,
    SyllabusOut,
    UserCreate,
    UserOut,
    UserStats,
    UserUpdate,
    TopicNotesOut,
    FlashcardOut,
    TopicDetailResponse,
    TopicProgressIn,
    TopicOut,
    AiLessonOut,
    AiTutorAskIn,
    AiTutorAskOut,
    CourseDetailOut,
    CourseIn,
    CourseMistakeIn,
    CourseMistakeOut,
    CourseModuleIn,
    CourseModuleOut,
    CourseQuestionIn,
    CourseQuestionOut,
    CourseTaskIn,
    CourseTaskOut,
    CourseOut,
    SubjectIn,
    SubjectOut,
)
from backend.repository import (
    answer_mock_question,
    create_course,
    create_course_mistake,
    create_course_module,
    create_course_question,
    create_course_task,
    create_mock_attempt,
    create_mock_test,
    create_scraper_source,
    create_subject,
    create_user,
    delete_course,
    delete_course_mistake,
    delete_course_module,
    delete_course_question,
    delete_course_task,
    delete_mock_test,
    delete_report,
    archive_scraper_source,
    delete_subject,
    delete_syllabus,
    delete_user,
    get_course,
    get_course_detail,
    get_course_mistake,
    get_course_module,
    get_course_question,
    get_course_task,
    get_mock_attempt,
    get_mock_test,
    get_question,
    get_scraper_source_by_url,
    get_syllabus,
    get_user,
    get_user_by_email,
    get_user_stats,
    insert_question,
    insert_syllabus,
    list_course_mistakes,
    list_course_modules,
    list_course_questions,
    list_course_tasks,
    list_courses,
    list_mock_tests,
    list_questions,
    list_questions_admin,
    list_reports,
    list_scraped_documents,
    list_scraper_runs,
    list_scraper_sources,
    list_subjects,
    list_syllabus,
    list_users,
    search_questions,
    submit_mock_attempt,
    list_preparation_subjects,
    list_preparation_topics,
    get_preparation_topic,
    save_topic_progress,
    get_ai_lesson,
    ai_tutor_ask,
    update_mock_test,
    update_course,
    update_course_mistake,
    update_course_module,
    update_course_question,
    update_course_task,
    update_question,
    update_report_status,
    update_scraper_source,
    update_subject,
    update_syllabus,
    update_user,
    utc_iso_now,
)
from backend.security import (
    create_session,
    device_hash,
    get_bearer_or_cookie_token,
    get_current_user,
    hash_password,
    normalize_email,
    rate_limit,
    require_admin_user,
    sign_payload,
    token_hash,
    validate_csrf_token,
    verify_password,
)
from backend.scraper import run_scraper
from backend.settings import settings
from backend.text import normalize_text


logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ADMIN_ASSETS = Path(__file__).resolve().parent / "admin_assets"
DASHBOARD_DIST = Path(__file__).resolve().parents[1] / "admin-dashboard" / "dist"
ARCHITECTURE_PAGE = PROJECT_ROOT / "index.html"
ARCHITECTURE_SPEC = PROJECT_ROOT / "ARCHITECTURE.md"

AI_DISCLAIMER = (
    "This answer was generated by an on-device AI model and may be incomplete "
    "or inaccurate. Please verify important facts with official sources such "
    "as Rajpatra or authoritative textbooks."
)


def startup() -> None:
    initialize_database()
    with get_connection() as connection:
        if not get_metadata(connection, "data_version", ""):
            set_metadata(connection, "data_version", "1")
        ensure_bootstrap_admin(connection)
        seed_sample_questions(connection)
        ensure_sample_mock_test(connection)
        seed_learning_catalog(connection)
        seed_preparation_materials(connection)
        ensure_scraper_sources(connection)


def ensure_scraper_sources(connection) -> None:
    for url in settings.scraper_target_urls:
        if get_scraper_source_by_url(connection, url) is not None:
            continue
        parsed = urlparse(url)
        domain = parsed.netloc.lower()
        name = domain.removeprefix("www.") or "Configured source"
        try:
            create_scraper_source(
                connection,
                ScraperSourceIn(
                    name=f"{name} live updates",
                    start_url=url,
                    allowed_domain=domain,
                    syllabus_category="",
                    max_depth=1,
                    max_pages=settings.scraper_max_pages_per_source,
                    refresh_minutes=max(5, settings.scraper_refresh_interval_seconds // 60),
                    status="active",
                ),
            )
        except sqlite3.IntegrityError:
            logger.info("Scraper source already exists for %s", url)


def seed_preparation_materials(connection) -> None:
    """Pre-populate dynamic subject topics and flashcards for study preparation module."""
    cnt = connection.execute("SELECT COUNT(*) AS count FROM topic_notes").fetchone()["count"]
    if cnt > 0:
        return

    topics = [
        {
            "subject_id": "Constitution",
            "title": "Introduction to the Constitution of Nepal",
            "content_beginner": "The Constitution of Nepal is the supreme law of the land. It was promulgated on 20 September 2015 (3 Ashoj 2072 BS) by the Constituent Assembly.",
            "content_intermediate": "The current Constitution of Nepal consists of 35 Parts, 308 Articles, and 9 Schedules. It replaced the Interim Constitution of 2063 BS. It defines Nepal as a federal democratic republic with three levels of governance: Federal, Provincial, and Local.",
            "content_advanced": "The constitution was promulgated by the second Constituent Assembly under the presidency of Ram Baran Yadav and Prime Minister Sushil Koirala. It represents a historic transition to federalism, with key characteristics such as cooperative federalism, secularism, and constitutional guarantees for inclusion.",
            "revision_notes": "- Promulgation date: 2072 Ashoj 3 (20 Sept 2015)\n- Structure: 35 Parts, 308 Articles, 9 Schedules\n- Concept: Federal Democratic Republic, Secular state, 3 tiers of government",
            "flashcards": [
                {"front": "When was the current Constitution of Nepal promulgated?", "back": "2072 Ashoj 3 (September 20, 2015)"},
                {"front": "How many Articles are there in the Constitution of Nepal?", "back": "308 Articles (under 35 Parts and 9 Schedules)"}
            ]
        },
        {
            "subject_id": "Constitution",
            "title": "Fundamental Rights of Citizens",
            "content_beginner": "Fundamental Rights are basic human rights guaranteed by the constitution to every citizen. Part 3 of the Constitution of Nepal lists these rights.",
            "content_intermediate": "There are 31 Fundamental Rights guaranteed under Articles 16 to 46 in Part 3 of the Constitution of Nepal. These range from the Right to live with dignity (Art 16) to the Right to constitutional remedies (Art 46).",
            "content_advanced": "Unlike ordinary legal rights, fundamental rights are constitutional guarantees enforceable directly through the Supreme Court under Article 46. Key rights include the Right of victim of crime (Art 21), Right against torture (Art 22), and Right to free secondary education (Art 31).",
            "revision_notes": "- Rights: 31 fundamental rights\n- Location: Part 3, Articles 16-46\n- Key Article: Article 46 (Right to constitutional remedies via Supreme Court)",
            "flashcards": [
                {"front": "How many Fundamental Rights are guaranteed by the Constitution of Nepal?", "back": "31 rights (from Article 16 to 46)"},
                {"front": "Which article guarantees the Right to live with dignity?", "back": "Article 16 (no law shall make provision for capital punishment)"}
            ]
        },
        {
            "subject_id": "Geography",
            "title": "Mountains and Peaks of Nepal",
            "content_beginner": "Nepal is home to the highest mountains in the world. The northern border is dominated by the Himalayan range, including Mount Everest.",
            "content_intermediate": "Nepal contains 8 of the 14 highest peaks in the world (above 8,000 meters). This includes Mount Everest (8848.86m), Kangchenjunga (8586m), Lhotse (8516m), Makalu (8485m), Cho Oyu (8188m), Dhaulagiri (8167m), Manaslu (8163m), and Annapurna (8091m).",
            "content_advanced": "Mountain ranges are geographically categorized into sections such as Mahalangur range (home to Everest, Lhotse, Cho Oyu) and Annapurna range. In 2020, Nepal and China jointly announced Everest's official height as 8848.86 meters.",
            "revision_notes": "- World's highest peaks in Nepal: 8 peaks above 8,000m\n- Mount Everest height: 8848.86 meters\n- Mahalangur range: Home of Everest",
            "flashcards": [
                {"front": "What is the official height of Mount Everest?", "back": "8,848.86 meters (jointly announced in 2020)"},
                {"front": "How many peaks above 8,000m are in Nepal?", "back": "8 peaks out of 14 in the world"}
            ]
        },
        {
            "subject_id": "History",
            "title": "Unification Campaign of Nepal",
            "content_beginner": "Nepal was unified by King Prithvi Narayan Shah of Gorkha. Before unification, Nepal was divided into many small principalities (Baise and Chaubise states).",
            "content_intermediate": "The unification campaign started in 1744 AD (1801 BS) with the conquest of Nuwakot. It succeeded in capturing Kathmandu in 1768 AD and Bhaktapur in 1769 AD, establishing Kathmandu as the capital of the unified Kingdom of Nepal.",
            "content_advanced": "Key military figures who shaped the campaign include Kaji Kalu Pande (who died in the first battle of Kirtipur), Bhakti Thapa, and Amar Singh Thapa (who led the westward expansion against British East India forces).",
            "revision_notes": "- Unification starter: King Prithvi Narayan Shah of Gorkha\n- Campaign start: 1744 AD (Nuwakot conquest)\n- Capture of Kathmandu: 1768 AD",
            "flashcards": [
                {"front": "Who is the Father of Unification of modern Nepal?", "back": "King Prithvi Narayan Shah of Gorkha"},
                {"front": "In which year was Kathmandu conquered by Gorkhali forces?", "back": "1768 AD (1825 BS)"}
            ]
        }
    ]

    for t in topics:
        cursor = connection.execute(
            """
            INSERT INTO topic_notes (subject_id, title, content_beginner, content_intermediate, content_advanced, revision_notes, verified)
            VALUES (?, ?, ?, ?, ?, ?, 1)
            """,
            (t["subject_id"], t["title"], t["content_beginner"], t["content_intermediate"], t["content_advanced"], t["revision_notes"])
        )
        topic_id = cursor.lastrowid
        for f in t["flashcards"]:
            connection.execute(
                """
                INSERT INTO flashcards (topic_id, front, back)
                VALUES (?, ?, ?)
                """,
                (topic_id, f["front"], f["back"])
            )



def ensure_bootstrap_admin(connection) -> None:
    existing_admin = connection.execute(
        "SELECT id FROM app_users WHERE role = 'admin' LIMIT 1"
    ).fetchone()
    if existing_admin is not None:
        return
    connection.execute(
        """
        INSERT INTO app_users (email, password_hash, full_name, role, status)
        VALUES (?, ?, ?, 'admin', 'active')
        """,
        (
            normalize_email(settings.bootstrap_admin_email),
            hash_password(settings.bootstrap_admin_password),
            settings.bootstrap_admin_name,
        ),
    )


def seed_sample_questions(connection) -> None:
    """Auto-seed questions from data/sample_questions.json if table is empty."""
    count_row = connection.execute(
        "SELECT COUNT(*) AS cnt FROM loksewa_questions"
    ).fetchone()
    if int(count_row["cnt"]) > 0:
        return

    sample_path = PROJECT_ROOT / "data" / "sample_questions.json"
    if not sample_path.exists():
        logger.warning("sample_questions.json not found at %s — skipping seed", sample_path)
        return

    with open(sample_path, "r", encoding="utf-8") as fh:
        questions_data = json.load(fh)

    version = int(get_metadata(connection, "data_version", "1"))
    seeded = 0
    for item in questions_data:
        q = QuestionIn(
            question_text=item["question_text"],
            option_a=item["option_a"],
            option_b=item["option_b"],
            option_c=item["option_c"],
            option_d=item["option_d"],
            correct_option=item["correct_option"],
            explanation=item.get("explanation", ""),
            syllabus_category=item.get("syllabus_category", ""),
            source_name=item.get("source_name", "Sample seed data"),
            source_license=item.get("source_license", "Internal sample data"),
            source_year=item.get("source_year"),
            source_page=item.get("source_page"),
            verifier=item.get("verifier", "development_seed"),
            verified_at=item.get("verified_at"),
            verification_status="verified",
        )
        try:
            insert_question(connection, q, data_version=version)
            seeded += 1
        except Exception as exc:
            logger.warning("Failed to seed question: %s", exc)

    logger.info("Seeded %d questions from sample_questions.json", seeded)


def ensure_sample_mock_test(connection) -> None:
    """Create 3 diverse mock tests if none exist yet."""
    existing = connection.execute("SELECT id FROM mock_tests LIMIT 1").fetchone()
    if existing is not None:
        return

    mock_definitions = [
        {
            "title": "Constitution & Governance Practice",
            "description": "Focused practice on Constitution and Governance topics.",
            "categories": ["Constitution", "Governance"],
            "question_count": 20,
            "duration_minutes": 30,
        },
        {
            "title": "General Knowledge Mixed Set",
            "description": "Mixed practice covering General Knowledge, Geography, and History.",
            "categories": ["General Knowledge", "Geography", "History"],
            "question_count": 25,
            "duration_minutes": 45,
        },
        {
            "title": "Full Loksewa Practice Exam",
            "description": "Comprehensive practice exam covering all categories.",
            "categories": [],  # all categories
            "question_count": 50,
            "duration_minutes": 60,
        },
    ]

    for defn in mock_definitions:
        if defn["categories"]:
            placeholders = ", ".join("?" for _ in defn["categories"])
            rows = connection.execute(
                f"""
                SELECT id
                FROM loksewa_questions
                WHERE verification_status = 'verified'
                  AND syllabus_category IN ({placeholders})
                ORDER BY id ASC
                LIMIT ?
                """,
                (*defn["categories"], defn["question_count"]),
            ).fetchall()
        else:
            rows = connection.execute(
                """
                SELECT id
                FROM loksewa_questions
                WHERE verification_status = 'verified'
                ORDER BY id ASC
                LIMIT ?
                """,
                (defn["question_count"],),
            ).fetchall()

        if not rows:
            logger.info(
                "Skipping mock test '%s': not enough verified questions",
                defn["title"],
            )
            continue

        mock = MockTestIn(
            title=defn["title"],
            description=defn["description"],
            exam_level="General",
            exam_type="MCQ",
            syllabus_category=", ".join(defn["categories"]) if defn["categories"] else "Mixed",
            duration_minutes=defn["duration_minutes"],
            marks_per_correct=1.0,
            negative_marking_enabled=True,
            negative_marks_per_wrong=0.2,
            status="published",
            question_ids=[int(row["id"]) for row in rows],
        )
        create_mock_test(connection, mock, created_by=None)
        logger.info(
            "Created mock test '%s' with %d questions",
            defn["title"],
            len(rows),
        )


def seed_learning_catalog(connection) -> None:
    """Seed API-backed learning content used by the mobile course screens."""
    existing = connection.execute("SELECT id FROM learning_subjects LIMIT 1").fetchone()
    if existing is not None:
        return

    subjects = [
        SubjectIn(slug="gk", title="General Knowledge", description="Static GK, current affairs, Nepal facts, science, history, and geography.", icon="public", color="#635BFF", sort_order=1),
        SubjectIn(slug="iq", title="IQ and Reasoning", description="Patterns, series, analogy, coding, direction, and fast elimination practice.", icon="psychology", color="#10AFA2", sort_order=2),
        SubjectIn(slug="law", title="Constitution and Law", description="Articles, rights, duties, governance bodies, and legal keyword traps.", icon="gavel", color="#F59E0B", sort_order=3),
        SubjectIn(slug="admin", title="Public Administration", description="Policy, accountability, ethics, service delivery, and case-based decisions.", icon="business", color="#3B82F6", sort_order=4),
    ]

    subject_ids: dict[str, int] = {}
    for subject in subjects:
        created = create_subject(connection, subject)
        subject_ids[subject.slug] = created.id

    course_payloads = [
        CourseIn(
            subject_id=subject_ids["gk"],
            slug="gk",
            short_name="GK",
            title="General Knowledge Mastery",
            badge="Popular GK",
            description="High-frequency facts, current affairs, science, geography, history, and Nepal-specific exam recall.",
            coach_line="High-frequency facts, current affairs, and quick recall practice.",
            plan_line="6 min fact review, 20 prediction questions, 8 flashcards, 1 mistake retry.",
            teacher="Aruna Sharma",
            lesson_count=45,
            duration="8 weeks",
            level="Officer",
            progress=64,
            ai_score=73,
            icon="public",
            color="#635BFF",
            background="#EEEAFE",
            sort_order=1,
        ),
        CourseIn(
            subject_id=subject_ids["iq"],
            slug="iq",
            short_name="IQ",
            title="IQ and Reasoning Accelerator",
            badge="Speed Logic",
            description="Pattern recognition, series, analogy, coding, direction, and elimination under exam timing.",
            coach_line="Pattern recognition, series, analogy, and speed logic drills.",
            plan_line="Warm up shortcuts, solve timed sets, explain wrong patterns, retry slow items.",
            teacher="Rabin K.C.",
            lesson_count=32,
            duration="6 weeks",
            level="Beginner",
            progress=48,
            ai_score=68,
            icon="psychology",
            color="#10AFA2",
            background="#E4FAF7",
            sort_order=2,
        ),
        CourseIn(
            subject_id=subject_ids["law"],
            slug="law",
            short_name="Law",
            title="Constitution and Law Essentials",
            badge="Exam Trap",
            description="Articles, rights, duties, governance structure, commissions, and negative wording traps.",
            coach_line="Articles, rights, governance structure, and keyword traps.",
            plan_line="Article recall, keyword trap practice, provision mapping, and mini mock.",
            teacher="Maya Adhikari",
            lesson_count=28,
            duration="5 weeks",
            level="Intermediate",
            progress=42,
            ai_score=61,
            icon="gavel",
            color="#F59E0B",
            background="#FFF4D8",
            sort_order=3,
        ),
        CourseIn(
            subject_id=subject_ids["admin"],
            slug="admin",
            short_name="Admin",
            title="Public Administration Practice",
            badge="Policy Skill",
            description="Administration principles, accountability, public service delivery, policy cycle, and practical cases.",
            coach_line="Policy, management, accountability, and service delivery concepts.",
            plan_line="Concept review, scenario selection, weak term flashcards, and case retry.",
            teacher="Suman Bista",
            lesson_count=24,
            duration="4 weeks",
            level="Officer",
            progress=37,
            ai_score=58,
            icon="business",
            color="#3B82F6",
            background="#E8F1FF",
            sort_order=4,
        ),
    ]

    courses = {payload.slug: create_course(connection, payload) for payload in course_payloads}

    modules = {
        "gk": [
            ("Nepal geography and history", 12, "1 hr 45 min", 80, False),
            ("Current affairs recall", 10, "1 hr 20 min", 54, False),
            ("Science and technology facts", 11, "1 hr 30 min", 28, False),
            ("Mixed GK mock confirmation", 12, "2 hr", 0, True),
        ],
        "iq": [
            ("Number and letter series", 8, "1 hr", 65, False),
            ("Analogy and classification", 8, "1 hr 10 min", 44, False),
            ("Direction and coding", 8, "1 hr 15 min", 22, False),
            ("Timed reasoning mock", 8, "1 hr 30 min", 0, True),
        ],
        "law": [
            ("Fundamental rights and duties", 8, "1 hr 15 min", 58, False),
            ("State structure and bodies", 7, "1 hr", 38, False),
            ("Article number recall", 7, "55 min", 18, False),
            ("Negative keyword practice", 6, "50 min", 0, True),
        ],
        "admin": [
            ("Administration principles", 7, "1 hr", 48, False),
            ("Accountability and ethics", 6, "45 min", 36, False),
            ("Policy cycle", 5, "40 min", 18, False),
            ("Applied case practice", 6, "1 hr", 0, True),
        ],
    }

    for slug, rows in modules.items():
        for index, (title, lessons, duration, progress, locked) in enumerate(rows, start=1):
            create_course_module(
                connection,
                courses[slug].id,
                CourseModuleIn(title=title, lessons=lessons, duration=duration, progress=progress, locked=locked, sort_order=index),
            )

    task_rows = [
        ("gk", "Daily Prediction Set", "20 high-frequency GK questions with instant answer reasoning.", "12 min", "question_answer", 3, "Medium", "GK set ready", "AI will score recall speed and flag current affairs that need spaced revision."),
        ("gk", "Rapid Fact Flashcards", "Memorize dates, institutions, awards, geography, and science facts.", "7 min", "bookmark", 2, "Easy", "Flashcards ready", "Slow cards will be pinned to tomorrow's revision queue."),
        ("iq", "Speed Reasoning Drill", "Series, analogy, coding, direction, and odd-one-out under time.", "15 min", "timer", 4, "Hard", "Speed drill ready", "AI will mark time pressure, skipped steps, and shortcut opportunities."),
        ("iq", "Step-by-step Logic", "See why each option fails before selecting the final answer.", "9 min", "insights", 3, "Medium", "Logic flow ready", "The coach compares your reasoning path with the optimal shortcut."),
        ("law", "Article Recall Sprint", "Practice Constitution article numbers, rights, duties, and bodies.", "11 min", "gavel", 4, "Hard", "Law recall ready", "AI will detect article sequence confusion and generate a smaller recall chain."),
        ("law", "Keyword Trap Practice", "Train on except, not, only, and similar exam wording traps.", "8 min", "error", 3, "Medium", "Keyword traps ready", "Wrong answers are grouped by trap type so you can retry with better attention."),
        ("admin", "Policy Concept Drill", "Connect administration principles with real Loksewa-style examples.", "13 min", "business", 3, "Medium", "Policy drill ready", "AI will compare theory recall against applied scenario selection."),
        ("admin", "Case Explanation", "Read a short case and select the most accountable decision.", "10 min", "book", 4, "Hard", "Case flow ready", "The coach explains why each distractor looks attractive but fails the rule."),
        (None, "Mini Mock Confirmation", "10 mixed questions to verify whether today's learning actually stuck.", "10 min", "assignment", 5, "Adaptive", "Mini mock ready", "The next mini mock mixes strong and weak topics so the score is not inflated."),
    ]

    for index, (slug, title, subtitle, duration, icon, score_boost, next_difficulty, alert_title, alert_message) in enumerate(task_rows, start=1):
        create_course_task(
            connection,
            CourseTaskIn(
                course_id=None if slug is None else courses[slug].id,
                title=title,
                subtitle=subtitle,
                duration=duration,
                icon=icon,
                score_boost=score_boost,
                next_difficulty=next_difficulty,
                alert_title=alert_title,
                alert_message=alert_message,
                sort_order=index,
            ),
        )

    question_rows = {
        "gk": [
            ("Learn and Practice", "Which method gives the strongest long-term recall for static GK facts?", "Only reading the same page many times", "Spaced active recall with short flashcards", "Watching one long lecture without practice", "Solving only full mocks", "B", "Spaced active recall forces retrieval and repeats weak facts over time. That is why the AI plan turns slow or wrong facts into tomorrow's cards.", "Think about a method that makes your brain retrieve the fact, not just see it again.", ["Recall", "Flashcard"]),
            ("Prediction Set", "In a GK exam, what should the AI mark as a weak signal after practice?", "Only wrong answers", "Wrong answers and slow correct answers", "Only skipped questions", "Only questions from history", "B", "A slow correct answer still means recall is fragile. The flow treats it as review material before it becomes a wrong answer under pressure.", "A correct answer can still be risky when it takes too long.", ["Speed", "Weakness"]),
        ],
        "iq": [
            ("Speed Drill", "What is the first check in a number series question?", "Guess from the options", "Difference, ratio, alternating pattern, then position logic", "Always multiply by two", "Skip the question immediately", "B", "A stable check order avoids wasting time. The AI flow records where your reasoning slowed down.", "Look for a repeatable checklist, not a single formula.", ["Shortcut", "Speed"]),
            ("Reasoning", "Why should you review wrong reasoning paths, not only final answers?", "It reveals the trap that caused the wrong answer", "It makes every question longer", "It removes the need for mocks", "It only helps vocabulary", "A", "Reasoning questions are won by path quality. AI feedback turns wrong paths into shorter retry drills.", "The answer alone does not show where your logic failed.", ["Trap", "Retry"]),
        ],
        "law": [
            ("Keyword Trap", "What is the safest first action in a negative law question?", "Ignore the negative word", "Circle the negative keyword and eliminate true statements", "Choose the longest option", "Skip all article questions", "B", "Negative wording changes the task. The AI flow separates keyword mistakes from knowledge mistakes.", "The question is asking for an exception, not the usual true statement.", ["Keyword", "Law"]),
            ("Article Recall", "Why does article recall need small chains instead of one big list?", "Small chains reduce sequence confusion", "Big lists are always faster", "Articles are not asked in exams", "It removes the need to revise", "A", "Short chains keep related provisions together and reduce article-number swapping.", "Think about preventing one provision from being mixed with another.", ["Recall", "Article"]),
        ],
        "admin": [
            ("Case Practice", "How is accountability different from transparency?", "They mean exactly the same thing", "Transparency is visibility, accountability is responsibility for action and result", "Accountability only means publishing data", "Transparency only applies to private offices", "B", "Many administration questions use close concepts. AI feedback flags term confusion and gives a contrast card.", "One term is about seeing action, the other is about being answerable for it.", ["Concept", "Contrast"]),
            ("Policy Drill", "Which step comes after policy implementation in a simple policy cycle?", "Evaluation", "Problem identification", "Agenda setting", "Drafting only", "A", "Implementation is followed by evaluation so the result can be measured and adjusted.", "After doing the policy, the system needs to check the result.", ["Policy", "Sequence"]),
        ],
    }

    for slug, rows in question_rows.items():
        for index, row in enumerate(rows, start=1):
            mode, prompt, option_a, option_b, option_c, option_d, correct_option, explanation, hint, tags = row
            create_course_question(
                connection,
                courses[slug].id,
                CourseQuestionIn(
                    mode=mode,
                    prompt=prompt,
                    option_a=option_a,
                    option_b=option_b,
                    option_c=option_c,
                    option_d=option_d,
                    correct_option=correct_option,
                    explanation=explanation,
                    hint=hint,
                    tags=tags,
                    sort_order=index,
                ),
            )

    mistake_rows = [
        ("gk", "Federalism fact mix-up", "Province and local level powers confused"),
        ("gk", "Current affairs recall", "Slow recall on recent appointments"),
        ("iq", "Number series shortcut", "Used long calculation instead of pattern"),
        ("iq", "Direction sense trap", "Skipped final orientation check"),
        ("law", "Article sequence recall", "Article number and provision mismatch"),
        ("law", "Except keyword missed", "Selected true statement in negative question"),
        ("admin", "Accountability concept", "Mixed transparency with responsibility"),
        ("admin", "Policy cycle order", "Evaluation placed before implementation"),
    ]
    for index, (slug, title, reason) in enumerate(mistake_rows, start=1):
        create_course_mistake(
            connection,
            courses[slug].id,
            CourseMistakeIn(title=title, reason=reason, sort_order=index),
        )

    logger.info("Seeded %d learning courses for API-backed mobile screens", len(courses))


async def scraper_refresh_loop() -> None:
    def run_due_sources() -> None:
        with get_connection() as connection:
            run_scraper(connection, due_only=True)

    await asyncio.sleep(3)
    while True:
        try:
            await asyncio.to_thread(run_due_sources)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("Background scraper refresh failed")
        await asyncio.sleep(settings.scraper_refresh_interval_seconds)


@asynccontextmanager
async def lifespan(_: FastAPI):
    # Validate settings on startup (fail-fast for security issues)
    from backend.settings import validate_settings
    validate_settings()
    startup()
    scraper_task = asyncio.create_task(scraper_refresh_loop()) if settings.scraper_enabled else None
    try:
        yield
    finally:
        if scraper_task is not None:
            scraper_task.cancel()
            try:
                await scraper_task
            except asyncio.CancelledError:
                pass


app = FastAPI(
    title=settings.app_name,
    version="0.1.0",
    docs_url="/docs" if settings.environment != "production" else None,
    redoc_url="/redoc" if settings.environment != "production" else None,
    dependencies=[Depends(rate_limit), Depends(validate_csrf_token)],
    lifespan=lifespan,
)

# HTTPS redirect only in production (trusted proxy sets X-Forwarded-Proto)
if settings.environment == "production":

    @app.middleware("http")
    async def https_redirect_middleware(request: Request, call_next):
        proto = request.headers.get("x-forwarded-proto", "http")
        if proto != "https":
            # Redirect all HTTP requests to HTTPS
            redirect_url = f"https://{request.url.hostname}{request.url.path}"
            if request.url.query:
                redirect_url += f"?{request.url.query}"
            from fastapi.responses import RedirectResponse

            return RedirectResponse(url=redirect_url, status_code=307)
        return await call_next(request)


# Request size limiting middleware (10MB for imports, 1MB for other requests)
@app.middleware("http")
async def limit_request_size(request: Request, call_next):
    if request.method in ("POST", "PUT", "PATCH", "DELETE"):
        path = request.url.path
        limit = 10 * 1024 * 1024 if "import" in path else 1 * 1024 * 1024

        content_length = request.headers.get("content-length")
        if content_length:
            try:
                if int(content_length) > limit:
                    from fastapi.responses import JSONResponse
                    return JSONResponse(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        content={"detail": "Request body too large"},
                    )
            except ValueError:
                from fastapi.responses import JSONResponse
                return JSONResponse(
                    status_code=status.HTTP_400_BAD_REQUEST,
                    content={"detail": "Invalid Content-Length header"},
                )

        # To prevent chunked encoding/slowloris bypass, wrap request receive
        original_receive = request._receive
        body_size = 0

        async def receive():
            nonlocal body_size
            message = await original_receive()
            if message["type"] == "http.request":
                body_size += len(message.get("body", b""))
                if body_size > limit:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail="Request body too large",
                    )
            return message

        request._receive = receive

    try:
        response = await call_next(request)
    except HTTPException as exc:
        if exc.status_code == status.HTTP_413_REQUEST_ENTITY_TOO_LARGE:
            from fastapi.responses import JSONResponse
            return JSONResponse(
                status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                content={"detail": exc.detail},
            )
        raise exc
    return response


app.add_middleware(
    CORSMiddleware,
    allow_origins=list(settings.cors_origins),
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allow_headers=["Content-Type", "X-Admin-Token", "Authorization", "X-CSRF-Token"],
)

if ADMIN_ASSETS.exists():
    app.mount("/admin-assets", StaticFiles(directory=ADMIN_ASSETS), name="admin-assets")
if DASHBOARD_DIST.exists():
    app.mount("/dashboard", StaticFiles(directory=DASHBOARD_DIST, html=True), name="dashboard")


def require_admin_access(
    request: Request,
    x_admin_token: str | None = Header(default=None),
) -> UserOut | None:
    if x_admin_token and hmac.compare_digest(x_admin_token, settings.admin_token):
        return None
    return require_admin_user(request)


def set_auth_cookie(response: Response, token: str, expires_at: str) -> None:
    response.set_cookie(
        key="loksewa_session",
        value=token,
        httponly=True,
        secure=settings.environment == "production",
        samesite="lax",
        expires=expires_at,
        path="/",
    )


@app.get("/admin")
def admin_panel() -> FileResponse:
    index = ADMIN_ASSETS / "index.html"
    if not index.exists():
        raise HTTPException(status_code=404, detail="Admin assets not found")
    return FileResponse(index)


@app.get("/")
@app.get("/architecture")
def architecture_page() -> FileResponse:
    if not ARCHITECTURE_PAGE.exists():
        raise HTTPException(status_code=404, detail="Architecture page not found")
    return FileResponse(ARCHITECTURE_PAGE)


@app.get("/architecture.md")
def architecture_markdown() -> PlainTextResponse:
    if not ARCHITECTURE_SPEC.exists():
        raise HTTPException(status_code=404, detail="Architecture spec not found")
    return PlainTextResponse(ARCHITECTURE_SPEC.read_text(encoding="utf-8"))


@app.get("/healthz")
def healthz() -> dict[str, str]:
    return {"status": "ok", "environment": settings.environment}


@app.post("/v1/auth/register", response_model=AuthResponse, status_code=status.HTTP_201_CREATED)
def register(payload: RegisterRequest, response: Response) -> AuthResponse:
    with get_connection() as connection:
        if get_user_by_email(connection, payload.email):
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Email already registered")
        user = create_user(
            connection,
            UserCreate(
                email=payload.email,
                password=payload.password,
                full_name=payload.full_name,
                role="student",
                status="active",
            ),
        )
        token, expires_at, csrf_token = create_session(connection, user.id, "mobile")
    set_auth_cookie(response, token, expires_at)
    # Return CSRF token to client for subsequent state-changing requests
    response.set_cookie(
        key="loksewa_csrf",
        value=csrf_token,
        httponly=False,  # Must be readable by JS for XHR double-submit
        secure=settings.environment == "production",
        samesite="strict",
        expires=expires_at,
        path="/",
    )
    return AuthResponse(token=token, user=user, expires_at=expires_at)


@app.post("/v1/auth/login", response_model=AuthResponse)
def login(payload: LoginRequest, response: Response) -> AuthResponse:
    with get_connection() as connection:
        row = get_user_by_email(connection, payload.email)
        if row is None or row["status"] != "active" or not verify_password(payload.password, row["password_hash"]):
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid email or password")
        user = UserOut(
            id=row["id"],
            email=row["email"],
            full_name=row["full_name"],
            role=row["role"],
            status=row["status"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            last_login_at=row["last_login_at"],
        )
        if payload.client_type == "admin" and user.role != "admin":
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Admin account required")
        token, expires_at, csrf_token = create_session(connection, user.id, payload.client_type)
    set_auth_cookie(response, token, expires_at)
    response.set_cookie(
        key="loksewa_csrf",
        value=csrf_token,
        httponly=False,
        secure=settings.environment == "production",
        samesite="strict",
        expires=expires_at,
        path="/",
    )
    return AuthResponse(token=token, user=user, expires_at=expires_at)


@app.get("/v1/auth/me", response_model=UserOut)
def me(user: UserOut = Depends(get_current_user)) -> UserOut:
    return user


@app.post("/v1/auth/logout", status_code=status.HTTP_204_NO_CONTENT)
def logout(request: Request, response: Response) -> Response:
    token = get_bearer_or_cookie_token(request)
    if token:
        with get_connection() as connection:
            connection.execute(
                "UPDATE auth_sessions SET revoked_at = CURRENT_TIMESTAMP WHERE token_hash = ?",
                (token_hash(token),),
            )
    response.delete_cookie("loksewa_session", path="/")
    response.status_code = status.HTTP_204_NO_CONTENT
    return response


@app.get("/v1/metadata")
def metadata() -> dict[str, str]:
    with get_connection() as connection:
        return {
            "schema_version": get_metadata(connection, "schema_version", "1"),
            "data_version": get_metadata(connection, "data_version", "1"),
            "database_kind": get_metadata(connection, "database_kind", "loksewa_backend"),
        }


@app.post("/v1/search", response_model=SearchResponse)
def search(payload: SearchRequest) -> SearchResponse:
    limit = min(payload.limit, settings.max_search_limit)
    with get_connection() as connection:
        raw_matches = search_questions(connection, payload.query, limit=limit)

    matches = [
        SearchMatch(question=question, bm25_score=bm25_score, similarity=similarity)
        for question, bm25_score, similarity in raw_matches
    ]

    best = matches[0].similarity if matches else 0.0
    if best >= settings.high_confidence_threshold:
        return SearchResponse(
            answer_source="verified_db",
            threshold_reason=f"Best trigram similarity {best:.2f} reached verified threshold.",
            query=payload.query,
            matches=matches,
        )

    if best >= settings.medium_confidence_threshold and payload.allow_ai_fallback:
        return SearchResponse(
            answer_source="ai_assisted",
            threshold_reason=f"Best trigram similarity {best:.2f} reached context threshold.",
            query=payload.query,
            matches=matches,
            disclaimer=AI_DISCLAIMER,
        )

    if payload.allow_ai_fallback:
        return SearchResponse(
            answer_source="ai_only",
            threshold_reason="No verified match passed the context threshold.",
            query=payload.query,
            matches=matches,
            disclaimer=AI_DISCLAIMER,
        )

    return SearchResponse(
        answer_source="uncertain",
        threshold_reason="No verified match and AI fallback is disabled.",
        query=payload.query,
        matches=matches,
    )


@app.get("/v1/questions", response_model=dict)
def questions(
    category: str | None = None,
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=20, ge=1, le=100),
) -> dict:
    with get_connection() as connection:
        all_items = list_questions(connection, category=category, limit=per_page * page)
        total = len(all_items)
        start = (page - 1) * per_page
        page_items = all_items[start:start + per_page]
        return {
            "page": page,
            "per_page": per_page,
            "total": total,
            "items": [item.model_dump(mode="json") for item in page_items],
        }


@app.get("/v1/questions/{question_id}", response_model=QuestionOut)
def question_detail(question_id: int) -> QuestionOut:
    with get_connection() as connection:
        question = get_question(connection, question_id)
    if question is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
    return question


@app.get("/v1/stats/me", response_model=UserStats)
def user_stats(user: UserOut = Depends(get_current_user)) -> UserStats:
    with get_connection() as connection:
        stats = get_user_stats(connection, user.id)
    return UserStats(**stats)


@app.get("/v1/mock-tests", response_model=list[MockTestOut])
def public_mock_tests(limit: int = Query(default=100, ge=1, le=500)) -> list[MockTestOut]:
    with get_connection() as connection:
        return list_mock_tests(connection, status="published", limit=limit)


@app.get("/v1/subjects", response_model=list[SubjectOut])
def public_subjects(limit: int = Query(default=100, ge=1, le=500)) -> list[SubjectOut]:
    with get_connection() as connection:
        return list_subjects(connection, status="published", limit=limit)


@app.get("/v1/courses", response_model=list[CourseOut])
def public_courses(
    subject_id: int | None = None,
    limit: int = Query(default=100, ge=1, le=500),
) -> list[CourseOut]:
    with get_connection() as connection:
        return list_courses(connection, subject_id=subject_id, status="published", limit=limit)


@app.get("/v1/courses/{course_identifier}", response_model=CourseDetailOut)
def public_course_detail(course_identifier: str) -> CourseDetailOut:
    with get_connection() as connection:
        detail = get_course_detail(connection, course_identifier, published_only=True)
    if detail is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Published course not found")
    return detail


@app.post("/v1/mock-tests/{mock_test_id}/start", response_model=MockAttemptOut, status_code=status.HTTP_201_CREATED)
def start_mock_test(mock_test_id: int, user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    with get_connection() as connection:
        attempt = create_mock_attempt(connection, mock_test_id, user.id)
    if attempt is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Published mock test not found")
    return attempt


@app.get("/v1/mock-attempts/{attempt_id}", response_model=MockAttemptOut)
def mock_attempt_detail(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    with get_connection() as connection:
        attempt = get_mock_attempt(connection, attempt_id, user_id=user.id, include_questions=True)
    if attempt is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attempt not found")
    return attempt


@app.post("/v1/mock-attempts/{attempt_id}/answers", response_model=MockAttemptOut)
def answer_mock(attempt_id: int, payload: MockAnswerRequest, user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    with get_connection() as connection:
        attempt = answer_mock_question(connection, attempt_id, user.id, payload)
    if attempt is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Cannot answer this question")
    return attempt


@app.post("/v1/mock-attempts/{attempt_id}/submit", response_model=MockSubmitResponse)
def submit_mock(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockSubmitResponse:
    with get_connection() as connection:
        result = submit_mock_attempt(connection, attempt_id, user.id)
    if result is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attempt not found")
    return result


@app.get("/v1/sync/delta", response_model=DeltaResponse)
def sync_delta(
    since_version: int = Query(default=0, ge=0),
    limit: int = Query(default=500, ge=1, le=5000),
) -> DeltaResponse:
    with get_connection() as connection:
        to_version = int(get_metadata(connection, "data_version", "1"))
        questions = list_questions(connection, since_version=since_version, limit=limit)

    payload = {
        "from_version": since_version,
        "to_version": to_version,
        "questions": [question.model_dump(mode="json") for question in questions],
    }
    return DeltaResponse(
        from_version=since_version,
        to_version=to_version,
        questions=questions,
        signature=sign_payload(payload),
    )


@app.post("/v1/reports", response_model=ReportResponse, status_code=status.HTTP_201_CREATED)
def create_report(payload: ReportRequest) -> ReportResponse:
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO user_reports (
                question_id,
                scanned_text,
                report_type,
                message,
                contact,
                device_hash
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                payload.question_id,
                payload.scanned_text,
                payload.report_type,
                payload.message,
                payload.contact,
                device_hash(payload.device_id),
            ),
        )
        report_id = int(cursor.lastrowid)
    return ReportResponse(report_id=report_id, status="open")


@app.get(
    "/v1/admin/scraper/sources",
    response_model=list[ScraperSourceOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_scraper_sources(
    source_status: str | None = None,
    due_only: bool = False,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[ScraperSourceOut]:
    with get_connection() as connection:
        return list_scraper_sources(connection, status=source_status, due_only=due_only, limit=limit)


@app.post(
    "/v1/admin/scraper/sources",
    response_model=ScraperSourceOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_scraper_source(payload: ScraperSourceIn) -> ScraperSourceOut:
    try:
        with get_connection() as connection:
            return create_scraper_source(connection, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Scraper source could not be saved: {exc}") from exc


@app.put(
    "/v1/admin/scraper/sources/{source_id}",
    response_model=ScraperSourceOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_scraper_source(source_id: int, payload: ScraperSourceIn) -> ScraperSourceOut:
    try:
        with get_connection() as connection:
            updated = update_scraper_source(connection, source_id, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Scraper source could not be saved: {exc}") from exc
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Scraper source not found")
    return updated


@app.delete(
    "/v1/admin/scraper/sources/{source_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_archive_scraper_source(source_id: int) -> Response:
    with get_connection() as connection:
        archived = archive_scraper_source(connection, source_id)
    if not archived:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Scraper source not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.post(
    "/v1/admin/scraper/run",
    response_model=list[ScraperRunOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_run_scraper(payload: ScraperRunRequest) -> list[ScraperRunOut]:
    with get_connection() as connection:
        runs = run_scraper(
            connection,
            source_id=payload.source_id,
            due_only=False,
            max_pages=payload.max_pages,
        )
    if payload.source_id is not None and not runs:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Active scraper source not found")
    return runs


@app.get(
    "/v1/admin/scraper/runs",
    response_model=list[ScraperRunOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_scraper_runs(limit: int = Query(default=100, ge=1, le=500)) -> list[ScraperRunOut]:
    with get_connection() as connection:
        return list_scraper_runs(connection, limit=limit)


@app.get(
    "/v1/admin/scraper/documents",
    response_model=list[ScrapedDocumentOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_scraped_documents(
    source_id: int | None = None,
    category: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[ScrapedDocumentOut]:
    with get_connection() as connection:
        return list_scraped_documents(connection, source_id=source_id, category=category, limit=limit)


@app.get(
    "/v1/admin/subjects",
    response_model=list[SubjectOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_subjects(
    subject_status: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[SubjectOut]:
    with get_connection() as connection:
        return list_subjects(connection, status=subject_status, limit=limit)


@app.post(
    "/v1/admin/subjects",
    response_model=SubjectOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_subject(payload: SubjectIn) -> SubjectOut:
    try:
        with get_connection() as connection:
            return create_subject(connection, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Subject could not be saved: {exc}") from exc


@app.put(
    "/v1/admin/subjects/{subject_id}",
    response_model=SubjectOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_subject(subject_id: int, payload: SubjectIn) -> SubjectOut:
    try:
        with get_connection() as connection:
            updated = update_subject(connection, subject_id, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Subject could not be saved: {exc}") from exc
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Subject not found")
    return updated


@app.delete(
    "/v1/admin/subjects/{subject_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_subject(subject_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_subject(connection, subject_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Subject not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/courses",
    response_model=list[CourseOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_courses(
    subject_id: int | None = None,
    course_status: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[CourseOut]:
    with get_connection() as connection:
        return list_courses(connection, subject_id=subject_id, status=course_status, limit=limit)


@app.post(
    "/v1/admin/courses",
    response_model=CourseOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_course(payload: CourseIn) -> CourseOut:
    try:
        with get_connection() as connection:
            return create_course(connection, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Course could not be saved: {exc}") from exc


@app.get(
    "/v1/admin/courses/{course_id}/detail",
    response_model=CourseDetailOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_course_detail(course_id: int) -> CourseDetailOut:
    with get_connection() as connection:
        detail = get_course_detail(connection, str(course_id), published_only=False)
    if detail is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
    return detail


@app.put(
    "/v1/admin/courses/{course_id}",
    response_model=CourseOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_course(course_id: int, payload: CourseIn) -> CourseOut:
    try:
        with get_connection() as connection:
            updated = update_course(connection, course_id, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Course could not be saved: {exc}") from exc
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
    return updated


@app.delete(
    "/v1/admin/courses/{course_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_course(course_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_course(connection, course_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/courses/{course_id}/modules",
    response_model=list[CourseModuleOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_course_modules(course_id: int) -> list[CourseModuleOut]:
    with get_connection() as connection:
        return list_course_modules(connection, course_id)


@app.post(
    "/v1/admin/courses/{course_id}/modules",
    response_model=CourseModuleOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_course_module(course_id: int, payload: CourseModuleIn) -> CourseModuleOut:
    with get_connection() as connection:
        if get_course(connection, course_id) is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
        return create_course_module(connection, course_id, payload)


@app.put(
    "/v1/admin/course-modules/{module_id}",
    response_model=CourseModuleOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_course_module(module_id: int, payload: CourseModuleIn) -> CourseModuleOut:
    with get_connection() as connection:
        updated = update_course_module(connection, module_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course module not found")
    return updated


@app.delete(
    "/v1/admin/course-modules/{module_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_course_module(module_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_course_module(connection, module_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course module not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/courses/{course_id}/tasks",
    response_model=list[CourseTaskOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_course_tasks(course_id: int) -> list[CourseTaskOut]:
    with get_connection() as connection:
        return list_course_tasks(connection, course_id)


@app.post(
    "/v1/admin/courses/{course_id}/tasks",
    response_model=CourseTaskOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_course_task(course_id: int, payload: CourseTaskIn) -> CourseTaskOut:
    with get_connection() as connection:
        if get_course(connection, course_id) is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
        return create_course_task(connection, payload.model_copy(update={"course_id": course_id}))


@app.put(
    "/v1/admin/course-tasks/{task_id}",
    response_model=CourseTaskOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_course_task(task_id: int, payload: CourseTaskIn) -> CourseTaskOut:
    try:
        with get_connection() as connection:
            updated = update_course_task(connection, task_id, payload)
    except sqlite3.IntegrityError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=f"Course task could not be saved: {exc}") from exc
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course task not found")
    return updated


@app.delete(
    "/v1/admin/course-tasks/{task_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_course_task(task_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_course_task(connection, task_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course task not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/courses/{course_id}/questions",
    response_model=list[CourseQuestionOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_course_questions(course_id: int) -> list[CourseQuestionOut]:
    with get_connection() as connection:
        return list_course_questions(connection, course_id)


@app.post(
    "/v1/admin/courses/{course_id}/questions",
    response_model=CourseQuestionOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_course_question(course_id: int, payload: CourseQuestionIn) -> CourseQuestionOut:
    with get_connection() as connection:
        if get_course(connection, course_id) is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
        return create_course_question(connection, course_id, payload)


@app.put(
    "/v1/admin/course-questions/{question_id}",
    response_model=CourseQuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_course_question(question_id: int, payload: CourseQuestionIn) -> CourseQuestionOut:
    with get_connection() as connection:
        updated = update_course_question(connection, question_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course question not found")
    return updated


@app.delete(
    "/v1/admin/course-questions/{question_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_course_question(question_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_course_question(connection, question_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course question not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/courses/{course_id}/mistakes",
    response_model=list[CourseMistakeOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_course_mistakes(course_id: int) -> list[CourseMistakeOut]:
    with get_connection() as connection:
        return list_course_mistakes(connection, course_id)


@app.post(
    "/v1/admin/courses/{course_id}/mistakes",
    response_model=CourseMistakeOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_course_mistake(course_id: int, payload: CourseMistakeIn) -> CourseMistakeOut:
    with get_connection() as connection:
        if get_course(connection, course_id) is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course not found")
        return create_course_mistake(connection, course_id, payload)


@app.put(
    "/v1/admin/course-mistakes/{mistake_id}",
    response_model=CourseMistakeOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_course_mistake(mistake_id: int, payload: CourseMistakeIn) -> CourseMistakeOut:
    with get_connection() as connection:
        updated = update_course_mistake(connection, mistake_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course mistake not found")
    return updated


@app.delete(
    "/v1/admin/course-mistakes/{mistake_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_course_mistake(mistake_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_course_mistake(connection, mistake_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Course mistake not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/questions",
    response_model=list[QuestionOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_questions(
    verification_status: str | None = None,
    category: str | None = None,
    query: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[QuestionOut]:
    with get_connection() as connection:
        return list_questions_admin(
            connection,
            status=verification_status,
            category=category,
            query=query,
            limit=limit,
        )


@app.post(
    "/v1/admin/questions",
    response_model=QuestionOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_question(payload: QuestionIn) -> QuestionOut:
    with get_connection() as connection:
        version = next_data_version(connection)
        question_id = insert_question(connection, payload, data_version=version)
        created = get_question(connection, question_id)
    if created is None:
        raise HTTPException(status_code=500, detail="Question insert failed")
    return created


@app.get(
    "/v1/admin/questions/{question_id}",
    response_model=QuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_get_question(question_id: int) -> QuestionOut:
    return question_detail(question_id)


@app.put(
    "/v1/admin/questions/{question_id}",
    response_model=QuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_question(question_id: int, payload: QuestionIn) -> QuestionOut:
    with get_connection() as connection:
        version = next_data_version(connection)
        updated = update_question(connection, question_id, payload, data_version=version)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
    return updated


@app.post(
    "/v1/admin/import-batch",
    response_model=ImportBatchResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_import_batch(payload: ImportBatchRequest) -> ImportBatchResponse:
    imported_count = 0
    rejected_count = 0

    with get_connection() as connection:
        version = next_data_version(connection)
        cursor = connection.execute(
            """
            INSERT INTO import_batches (
                batch_name,
                source_name,
                source_url,
                source_license,
                verifier
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                payload.batch_name,
                payload.source_name,
                payload.source_url,
                payload.source_license,
                payload.verifier,
            ),
        )
        batch_id = int(cursor.lastrowid)

        for question in payload.questions:
            if not question.source_name:
                question.source_name = payload.source_name
            if not question.source_url:
                question.source_url = payload.source_url
            if not question.source_license:
                question.source_license = payload.source_license
            if not question.verifier:
                question.verifier = payload.verifier
            try:
                insert_question(
                    connection,
                    question,
                    data_version=version,
                    import_batch_id=batch_id,
                )
                imported_count += 1
            except Exception:
                rejected_count += 1

        connection.execute(
            """
            UPDATE import_batches
            SET imported_count = ?, rejected_count = ?
            WHERE id = ?
            """,
            (imported_count, rejected_count, batch_id),
        )

    return ImportBatchResponse(
        batch_id=batch_id,
        imported_count=imported_count,
        rejected_count=rejected_count,
        data_version=version,
    )


@app.delete(
    "/v1/admin/questions/{question_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_question(question_id: int) -> Response:
    with get_connection() as connection:
        now = utc_iso_now()
        cursor = connection.execute(
            "UPDATE loksewa_questions SET verification_status = 'rejected', deleted_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?",
            (now, question_id),
        )
        if cursor.rowcount == 0:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
        next_data_version(connection)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.post(
    "/v1/admin/questions/{question_id}/review",
    response_model=QuestionOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_review_question(question_id: int, payload: ReviewUpdateRequest) -> QuestionOut:
    with get_connection() as connection:
        version = next_data_version(connection)
        cursor = connection.execute(
            """
            UPDATE loksewa_questions
            SET
                verification_status = ?,
                source_name = CASE WHEN ? != '' THEN ? ELSE source_name END,
                source_url = CASE WHEN ? != '' THEN ? ELSE source_url END,
                source_license = CASE WHEN ? != '' THEN ? ELSE source_license END,
                verifier = CASE WHEN ? != '' THEN ? ELSE verifier END,
                verified_at = COALESCE(?, verified_at),
                data_version = ?,
                updated_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (
                payload.verification_status,
                payload.source_name,
                payload.source_name,
                payload.source_url,
                payload.source_url,
                payload.source_license,
                payload.source_license,
                payload.verifier,
                payload.verifier,
                payload.verified_at,
                version,
                question_id,
            ),
        )
        if cursor.rowcount == 0:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
        reviewed = get_question(connection, question_id)
    if reviewed is None:
        raise HTTPException(status_code=500, detail="Review update failed")
    return reviewed


@app.get(
    "/v1/admin/syllabus",
    response_model=list[SyllabusOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_syllabus(category: str | None = None, limit: int = Query(default=200, ge=1, le=1000)) -> list[SyllabusOut]:
    with get_connection() as connection:
        return list_syllabus(connection, category=category, limit=limit)


@app.post(
    "/v1/admin/syllabus",
    response_model=SyllabusOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_syllabus(payload: SyllabusIn) -> SyllabusOut:
    with get_connection() as connection:
        syllabus_id = insert_syllabus(connection, payload)
        created = get_syllabus(connection, syllabus_id)
    if created is None:
        raise HTTPException(status_code=500, detail="Syllabus insert failed")
    return created


@app.put(
    "/v1/admin/syllabus/{syllabus_id}",
    response_model=SyllabusOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_syllabus(syllabus_id: int, payload: SyllabusIn) -> SyllabusOut:
    with get_connection() as connection:
        updated = update_syllabus(connection, syllabus_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Syllabus entry not found")
    return updated


@app.delete(
    "/v1/admin/syllabus/{syllabus_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_syllabus(syllabus_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_syllabus(connection, syllabus_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Syllabus entry not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/reports",
    response_model=list[ReportOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_reports(report_status: str | None = None, limit: int = Query(default=200, ge=1, le=1000)) -> list[ReportOut]:
    with get_connection() as connection:
        return list_reports(connection, status=report_status, limit=limit)


@app.put(
    "/v1/admin/reports/{report_id}",
    response_model=ReportOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_report(report_id: int, payload: ReportUpdateRequest) -> ReportOut:
    with get_connection() as connection:
        updated = update_report_status(connection, report_id, payload.status)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return updated


@app.delete(
    "/v1/admin/reports/{report_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_report(report_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_report(connection, report_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Report not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/users",
    response_model=list[UserOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_users(
    role: str | None = None,
    user_status: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
) -> list[UserOut]:
    with get_connection() as connection:
        return list_users(connection, role=role, status=user_status, limit=limit)


@app.post(
    "/v1/admin/users",
    response_model=UserOut,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_admin_access)],
)
def admin_create_user(payload: UserCreate) -> UserOut:
    with get_connection() as connection:
        if get_user_by_email(connection, payload.email):
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail="Email already exists")
        return create_user(connection, payload)


@app.put(
    "/v1/admin/users/{user_id}",
    response_model=UserOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_user(user_id: int, payload: UserUpdate) -> UserOut:
    with get_connection() as connection:
        updated = update_user(connection, user_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return updated


@app.delete(
    "/v1/admin/users/{user_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_user(user_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_user(connection, user_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get(
    "/v1/admin/mock-tests",
    response_model=list[MockTestOut],
    dependencies=[Depends(require_admin_access)],
)
def admin_list_mock_tests(mock_status: str | None = None, limit: int = Query(default=200, ge=1, le=1000)) -> list[MockTestOut]:
    with get_connection() as connection:
        return list_mock_tests(connection, status=mock_status, limit=limit)


@app.post(
    "/v1/admin/mock-tests",
    response_model=MockTestOut,
    status_code=status.HTTP_201_CREATED,
)
def admin_create_mock_test(payload: MockTestIn, admin: UserOut | None = Depends(require_admin_access)) -> MockTestOut:
    with get_connection() as connection:
        return create_mock_test(connection, payload, created_by=None if admin is None else admin.id)


@app.put(
    "/v1/admin/mock-tests/{mock_test_id}",
    response_model=MockTestOut,
    dependencies=[Depends(require_admin_access)],
)
def admin_update_mock_test(mock_test_id: int, payload: MockTestIn) -> MockTestOut:
    with get_connection() as connection:
        updated = update_mock_test(connection, mock_test_id, payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Mock test not found")
    return updated


@app.delete(
    "/v1/admin/mock-tests/{mock_test_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_admin_access)],
)
def admin_delete_mock_test(mock_test_id: int) -> Response:
    with get_connection() as connection:
        deleted = delete_mock_test(connection, mock_test_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Mock test not found")
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get("/v1/categories")
def categories() -> list[dict[str, object]]:
    with get_connection() as connection:
        rows = connection.execute(
            """
            SELECT syllabus_category AS category, COUNT(*) AS total
            FROM loksewa_questions
            WHERE verification_status = 'verified'
            GROUP BY syllabus_category
            ORDER BY total DESC, category ASC
            """
        ).fetchall()
    return [{"category": row["category"], "total": row["total"]} for row in rows]


@app.get("/v1/preparation/subjects", response_model=list[str])
def preparation_subjects() -> list[str]:
    return list_preparation_subjects()


@app.get("/v1/preparation/subjects/{subject_id}/topics", response_model=list[TopicOut])
def preparation_topics(subject_id: str, user: UserOut = Depends(get_current_user)) -> list[TopicOut]:
    with get_connection() as connection:
        topics = list_preparation_topics(connection, subject_id, user.id)
    return [TopicOut(**t) for t in topics]


@app.get("/v1/preparation/topics/{topic_id}", response_model=TopicDetailResponse)
def preparation_topic_detail(topic_id: int, user: UserOut = Depends(get_current_user)) -> TopicDetailResponse:
    with get_connection() as connection:
        detail = get_preparation_topic(connection, topic_id, user.id)
    if detail is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Topic not found")
    return TopicDetailResponse(**detail)


@app.post("/v1/preparation/topics/{topic_id}/progress", status_code=status.HTTP_204_NO_CONTENT)
def update_topic_progress(topic_id: int, payload: TopicProgressIn, user: UserOut = Depends(get_current_user)) -> Response:
    with get_connection() as connection:
        save_topic_progress(connection, user.id, topic_id, payload.completion_percentage)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


@app.get("/v1/questions/{question_id}/ai-lesson", response_model=AiLessonOut)
def question_ai_lesson(question_id: int) -> AiLessonOut:
    with get_connection() as connection:
        lesson = get_ai_lesson(connection, question_id)
    if lesson is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Question not found")
    return AiLessonOut(**lesson)


@app.post("/v1/ai-tutor/ask", response_model=AiTutorAskOut)
def ask_ai_tutor(payload: AiTutorAskIn) -> AiTutorAskOut:
    with get_connection() as connection:
        ans = ai_tutor_ask(connection, payload.query)
    return AiTutorAskOut(**ans)


# /api compatibility routes matching ARCHITECTURE.md exactly.


@app.post("/api/auth/register", response_model=AuthResponse, status_code=status.HTTP_201_CREATED)
def api_auth_register(payload: RegisterRequest, response: Response) -> AuthResponse:
    return register(payload, response)


@app.post("/api/auth/login", response_model=AuthResponse)
def api_auth_login(payload: LoginRequest, response: Response) -> AuthResponse:
    return login(payload, response)


@app.post("/api/auth/refresh", response_model=AuthResponse)
def api_auth_refresh(response: Response, user: UserOut = Depends(get_current_user)) -> AuthResponse:
    with get_connection() as connection:
        current = get_user(connection, user.id)
        if current is None:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User not found")
        token, expires_at, csrf_token = create_session(connection, user.id, "mobile")
    set_auth_cookie(response, token, expires_at)
    response.set_cookie(
        key="loksewa_csrf",
        value=csrf_token,
        httponly=False,
        secure=settings.environment == "production",
        samesite="strict",
        expires=expires_at,
        path="/",
    )
    return AuthResponse(token=token, user=current, expires_at=expires_at)


@app.post("/api/auth/logout", status_code=status.HTTP_204_NO_CONTENT)
def api_auth_logout(request: Request, response: Response) -> Response:
    return logout(request, response)


@app.get("/api/users/me", response_model=UserOut)
def api_users_me(user: UserOut = Depends(get_current_user)) -> UserOut:
    return user


@app.put("/api/users/me", response_model=UserOut)
def api_users_me_update(payload: UserUpdate, user: UserOut = Depends(get_current_user)) -> UserOut:
    safe_payload = UserUpdate(
        email=payload.email,
        full_name=payload.full_name,
        password=payload.password,
        role=None,
        status=None,
    )
    with get_connection() as connection:
        updated = update_user(connection, user.id, safe_payload)
    if updated is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return updated


@app.get("/api/subjects")
def api_subjects() -> list[dict[str, str]]:
    return [{"id": subject, "name": subject} for subject in list_preparation_subjects()]


@app.get("/api/subjects/{subject_id}/topics", response_model=list[TopicOut])
def api_subject_topics(subject_id: str, user: UserOut = Depends(get_current_user)) -> list[TopicOut]:
    return preparation_topics(subject_id, user)


@app.get("/api/topics/{topic_id}/notes", response_model=TopicDetailResponse)
def api_topic_notes(topic_id: int, user: UserOut = Depends(get_current_user)) -> TopicDetailResponse:
    return preparation_topic_detail(topic_id, user)


@app.get("/api/topics/{topic_id}", response_model=TopicDetailResponse)
def api_topic_detail(topic_id: int, user: UserOut = Depends(get_current_user)) -> TopicDetailResponse:
    return preparation_topic_detail(topic_id, user)


@app.get("/api/questions/search", response_model=SearchResponse)
def api_questions_search(q: str = Query(min_length=3), limit: int = Query(default=3, ge=1, le=10)) -> SearchResponse:
    return search(SearchRequest(query=q, limit=limit, allow_ai_fallback=True))


@app.get("/api/questions", response_model=dict)
def api_questions(
    subject: str | None = None,
    topic: str | None = None,
    difficulty: str | None = None,
    page: int = Query(default=1, ge=1),
    per_page: int = Query(default=20, ge=1, le=100),
) -> dict:
    return questions(category=topic or subject, page=page, per_page=per_page)


@app.get("/api/questions/{question_id}", response_model=QuestionOut)
def api_question_detail(question_id: int) -> QuestionOut:
    return question_detail(question_id)


@app.get("/api/questions/{question_id}/answer")
def api_question_answer(question_id: int) -> dict[str, object]:
    question = question_detail(question_id)
    correct_text = getattr(question, f"option_{question.correct_option.lower()}")
    return {
        "question_id": question.id,
        "answer_source": "verified_db",
        "correct_option": question.correct_option,
        "correct_answer": correct_text,
        "explanation": question.explanation,
        "source_name": question.source_name,
        "source_year": question.source_year,
    }


@app.post("/api/scan")
def api_scan(payload: dict[str, object]) -> dict[str, object]:
    scanned_text = str(
        payload.get("scanned_text")
        or payload.get("text")
        or payload.get("query")
        or ""
    ).strip()
    if len(scanned_text) < 3:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="scanned_text is required")

    result = search(SearchRequest(query=scanned_text, limit=3, allow_ai_fallback=True))
    matched_question_id = result.matches[0].question.id if result.matches else None
    with get_connection() as connection:
        cursor = connection.execute(
            """
            INSERT INTO scan_history (
                scanned_text,
                normalized_scanned_text,
                matched_question_id,
                answer_source
            )
            VALUES (?, ?, ?, ?)
            """,
            (scanned_text, normalize_text(scanned_text), matched_question_id, result.answer_source),
        )
        scan_id = int(cursor.lastrowid)
    return {
        "id": scan_id,
        "status": "completed",
        "result": result.model_dump(mode="json"),
    }


@app.get("/api/scan/{scan_id}")
def api_scan_detail(scan_id: int) -> dict[str, object]:
    with get_connection() as connection:
        row = connection.execute(
            """
            SELECT id, scanned_text, matched_question_id, answer_source, created_at
            FROM scan_history
            WHERE id = ?
            """,
            (scan_id,),
        ).fetchone()
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Scan not found")
    return dict(row)


@app.get("/api/scan/{scan_id}/result")
def api_scan_result(scan_id: int) -> dict[str, object]:
    detail = api_scan_detail(scan_id)
    question = None
    if detail.get("matched_question_id"):
        question = question_detail(int(detail["matched_question_id"])).model_dump(mode="json")
    return {
        "scan": detail,
        "question": question,
    }


@app.post("/api/lessons/generate", response_model=AiLessonOut)
def api_lesson_generate(payload: dict[str, object]) -> AiLessonOut:
    raw_id = payload.get("question_id") or payload.get("questionId")
    if raw_id is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="question_id is required")
    return question_ai_lesson(int(raw_id))


@app.get("/api/lessons/{question_id}", response_model=AiLessonOut)
def api_lesson_detail(question_id: int) -> AiLessonOut:
    return question_ai_lesson(question_id)


@app.get("/api/flashcards", response_model=list[FlashcardOut])
def api_flashcards(topic: str | None = None, limit: int = Query(default=50, ge=1, le=200)) -> list[FlashcardOut]:
    with get_connection() as connection:
        if topic and topic.isdigit():
            rows = connection.execute(
                "SELECT id, question_id, topic_id, front, back FROM flashcards WHERE topic_id = ? LIMIT ?",
                (int(topic), limit),
            ).fetchall()
        elif topic:
            rows = connection.execute(
                """
                SELECT f.id, f.question_id, f.topic_id, f.front, f.back
                FROM flashcards f
                JOIN topic_notes t ON t.id = f.topic_id
                WHERE t.subject_id = ? OR t.title LIKE ?
                LIMIT ?
                """,
                (topic, f"%{topic}%", limit),
            ).fetchall()
        else:
            rows = connection.execute(
                "SELECT id, question_id, topic_id, front, back FROM flashcards LIMIT ?",
                (limit,),
            ).fetchall()
    return [FlashcardOut(**dict(row)) for row in rows]


@app.post("/api/flashcards/{flashcard_id}/review")
def api_flashcard_review(flashcard_id: int, payload: dict[str, object], user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    return {
        "flashcard_id": flashcard_id,
        "user_id": user.id,
        "status": "recorded",
        "rating": payload.get("rating"),
    }


@app.get("/api/progress", response_model=UserStats)
def api_progress(user: UserOut = Depends(get_current_user)) -> UserStats:
    return user_stats(user)


@app.put("/api/progress/{topic_id}", status_code=status.HTTP_204_NO_CONTENT)
def api_progress_update(topic_id: int, payload: TopicProgressIn, user: UserOut = Depends(get_current_user)) -> Response:
    return update_topic_progress(topic_id, payload, user)


@app.post("/api/tutor/chat", response_model=AiTutorAskOut)
def api_tutor_chat(payload: dict[str, object]) -> AiTutorAskOut:
    query = str(payload.get("query") or payload.get("message") or "").strip()
    if len(query) < 2:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="query is required")
    return ask_ai_tutor(AiTutorAskIn(query=query))


@app.get("/api/tutor/conversations")
def api_tutor_conversations(user: UserOut = Depends(get_current_user)) -> list[dict[str, object]]:
    return []


@app.post("/api/tutor/conversations", status_code=status.HTTP_201_CREATED)
def api_tutor_create_conversation(user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    return {"id": "local-session", "user_id": user.id, "title": "Local tutor session", "messages": []}


@app.get("/api/tutor/conversations/{conversation_id}/messages")
def api_tutor_messages(conversation_id: str, user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    return {"id": conversation_id, "user_id": user.id, "messages": []}


@app.get("/api/tests", response_model=list[MockTestOut])
def api_tests(limit: int = Query(default=100, ge=1, le=500)) -> list[MockTestOut]:
    return public_mock_tests(limit)


@app.post("/api/tests/start", response_model=MockAttemptOut, status_code=status.HTTP_201_CREATED)
def api_tests_start(payload: dict[str, object], user: UserOut = Depends(get_current_user)) -> MockAttemptOut:
    raw_id = payload.get("mock_test_id") or payload.get("test_id") or payload.get("id")
    if raw_id is None:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="mock_test_id is required")
    return start_mock_test(int(raw_id), user)


@app.post("/api/tests/{attempt_id}/submit", response_model=MockSubmitResponse)
def api_tests_submit(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockSubmitResponse:
    return submit_mock(attempt_id, user)


@app.get("/api/tests/{attempt_id}/results", response_model=MockSubmitResponse)
def api_tests_results(attempt_id: int, user: UserOut = Depends(get_current_user)) -> MockSubmitResponse:
    with get_connection() as connection:
        result = submit_mock_attempt(connection, attempt_id, user.id)
    if result is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attempt not found")
    return result


@app.get("/api/analytics/stats", response_model=UserStats)
def api_analytics_stats(user: UserOut = Depends(get_current_user)) -> UserStats:
    return user_stats(user)


@app.get("/api/analytics/weaknesses")
def api_analytics_weaknesses(user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    stats = user_stats(user)
    return {
        "weaknesses": stats.categories_studied[:3],
        "message": "Review categories where recent mock answers were incorrect or unanswered.",
    }


@app.get("/api/analytics/recommendations")
def api_analytics_recommendations(user: UserOut = Depends(get_current_user)) -> dict[str, object]:
    stats = user_stats(user)
    subjects = list_preparation_subjects()
    studied = set(stats.categories_studied)
    recommended = [subject for subject in subjects if subject not in studied][:3]
    return {
        "recommendations": recommended,
        "message": "Continue with verified topic notes, flashcards, and timed mock tests.",
    }
