// 20+ Mock Test configurations for Nepal Loksewa PSC exams

export const mockTests = [
  // --- Category Specific Mocks ---
  {
    title: "Constitution of Nepal Special Mock",
    description: "Test your knowledge on parts, articles, fundamental rights, and constitutional bodies.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Constitution",
    duration_minutes: 20,
    total_questions: 20,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Nepal Geography Speed Test",
    description: "Focus on rivers, lakes, mountains, districts, and ecological regions of Nepal.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Geography",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Nepal History Recall Mock",
    description: "Test historical dates, dynastic periods (Kirat, Licchavi, Malla, Rana), and unification details.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "History",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "IQ & Logical Reasoning Challenge",
    description: "Numerical series, verbal logic, and non-verbal pattern tests.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "IQ and Reasoning",
    duration_minutes: 30,
    total_questions: 20,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Public Administration Policy Drill",
    description: "Civil Service Act, Good Governance, ethics, and office management principles.",
    exam_level: "Officer",
    exam_type: "MCQ",
    syllabus_category: "Public Administration",
    duration_minutes: 20,
    total_questions: 20,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Law and Legislation Quick Practice",
    description: "Civil and Criminal Codes of Nepal, legal procedures, and rights.",
    exam_level: "Officer",
    exam_type: "MCQ",
    syllabus_category: "Law and Legislation",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Science and Technology Facts",
    description: "Basic sciences, IT policy, astronomy, and environmental conservation in Nepal.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Science and Technology",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Economics and Planning Test",
    description: "GDP indicators, development plans (15th/16th Plan), agriculture, and tourism data.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Economics",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "English Grammar & Tense Mock",
    description: "Tenses, active/passive voice, direct/indirect speech, prepositions, and vocabulary.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "English Language",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Nepali Vyakaran & Grammar Practice",
    description: "Nepali grammar, syntax, spelling correction, and word classification.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Nepali Language",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  
  // --- Level Specific Full Mocks ---
  {
    title: "Section Officer (Adhikrit) Full Mock 1",
    description: "Complete First Paper practice test following Section Officer syllabus rules (GK & IQ).",
    exam_level: "Officer",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 45,
    total_questions: 50,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Section Officer (Adhikrit) Full Mock 2",
    description: "Another full-length Section Officer MCQ Paper 1 covering GK, IQ, and English.",
    exam_level: "Officer",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 45,
    total_questions: 50,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Nayab Subba (Na.Su.) Full Mock 1",
    description: "Full mock exam tailored for Nayab Subba level aspirants (First Paper).",
    exam_level: "Nayab Subba",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 45,
    total_questions: 50,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Nayab Subba (Na.Su.) Full Mock 2",
    description: "Second mock exam for Nayab Subba level containing GK and IQ.",
    exam_level: "Nayab Subba",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 45,
    total_questions: 50,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Kharidar Level Full Mock 1",
    description: "Mock exam designed for Kharidar level (GK & IQ, First Paper).",
    exam_level: "Kharidar",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 45,
    total_questions: 50,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Kharidar Level Full Mock 2",
    description: "Another practice paper for Kharidar level preparation.",
    exam_level: "Kharidar",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 45,
    total_questions: 50,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  
  // --- Daily and Weekly Practice Sets ---
  {
    title: "Daily Loksewa GK Booster",
    description: "Quick 10 GK questions for daily morning self-evaluation.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 10,
    total_questions: 10,
    marks_per_correct: 1,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.2,
    status: "published"
  },
  {
    title: "Daily Loksewa IQ Drill",
    description: "Quick 10 IQ questions to test speed reasoning and shortcuts.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 12,
    total_questions: 10,
    marks_per_correct: 1,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.2,
    status: "published"
  },
  {
    title: "Weekly Grand Mock Challenge",
    description: "Test yourself with our weekly comprehensive Loksewa MCQ challenge.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Mixed",
    duration_minutes: 60,
    total_questions: 60,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  },
  {
    title: "Current Affairs Monthly Round-up",
    description: "MCQ questions testing major national and international news from the last month.",
    exam_level: "General",
    exam_type: "MCQ",
    syllabus_category: "Current Affairs",
    duration_minutes: 15,
    total_questions: 15,
    marks_per_correct: 2,
    negative_marking_enabled: true,
    negative_marks_per_wrong: 0.4,
    status: "published"
  }
];
